import type { POI } from "@/types";

export const ACTIVE_AGEING_CENTRES: POI[] = [
  {
    id: "aac-allkin-yishun",
    name: "Allkin AAC (Yishun)",
    lat: 1.426,
    lng: 103.84,
    category: "Active Ageing Centre",
    description:
      "Operated by Allkin. Programs include exercises, social activities, befriending, digital literacy workshops and community support for seniors aged 60+.",
    address: "Blk 604 Yishun St 61 #01-328, Singapore 760604",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6757 4495",
  },
  {
    id: "aac-amkfsc-ang-mo-kio-226d",
    name: "AMKFSC AAC (Ang Mo Kio 226D)",
    lat: 1.372,
    lng: 103.8378,
    category: "Active Ageing Centre",
    description:
      "Operated by AMKFSC Community Services. Programs include exercise sessions, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 226D Ang Mo Kio Ave 1 #01-02, Singapore 564226",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6453 6899",
  },
  {
    id: "aac-amkfsc-ang-mo-kio-645",
    name: "AMKFSC AAC (Ang Mo Kio 645)",
    lat: 1.3709,
    lng: 103.8568,
    category: "Active Ageing Centre",
    description:
      "Operated by AMKFSC Community Services. Programs include Tai Chi and strength training, social activities, befriending and outreach support for seniors aged 60+.",
    address: "Blk 645 Ang Mo Kio Ave 6 #01-4802, Singapore 560645",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6453 2495",
  },
  {
    id: "aac-amkfsc-cheng-san",
    name: "AMKFSC AAC (Cheng San)",
    lat: 1.3755,
    lng: 103.8526,
    category: "Active Ageing Centre",
    description:
      "Operated by AMKFSC Community Services. Programs include exercise classes, art and craft, health screening and community support for seniors aged 60+.",
    address: "Blk 528 Ang Mo Kio Ave 10 #01-2439, Singapore 560528",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6459 8887",
  },
  {
    id: "aac-amkfsc-kebun-baru",
    name: "AMKFSC AAC (Kebun Baru)",
    lat: 1.367,
    lng: 103.8388,
    category: "Active Ageing Centre",
    description:
      "Operated by AMKFSC Community Services. Programs include exercise programmes, social activities, digital literacy and buddying support for seniors aged 60+.",
    address: "Blk 165 Ang Mo Kio Ave 4 #01-454, Singapore 560165",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6456 1601",
  },
  {
    id: "aac-amkfsc-sengkang",
    name: "AMKFSC AAC (Sengkang)",
    lat: 1.3928,
    lng: 103.8949,
    category: "Active Ageing Centre",
    description:
      "Operated by AMKFSC Community Services. Programs include Zumba, social activities, befriending and community outreach for seniors aged 60+.",
    address: "Blk 265A Sengkang East Ave #01-01, Singapore 541265",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-apex-harmony-lodge-pasir-ris",
    name: "Apex Harmony Lodge AAC (Pasir Ris)",
    lat: 1.376,
    lng: 103.9623,
    category: "Active Ageing Centre",
    description:
      "Operated by Apex Harmony Lodge. Programs include exercises, social activities, befriending, health screening and community support for seniors aged 60+.",
    address: "10 Pasir Ris Drive 4 #01-01, Singapore 519455",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-awwa-ang-mo-kio",
    name: "AWWA AAC (Ang Mo Kio)",
    lat: 1.368,
    lng: 103.841,
    category: "Active Ageing Centre",
    description:
      "Operated by AWWA. Programs include exercise programmes, karaoke and social activities, health screening and community support for seniors aged 60+.",
    address: "Blk 122 Ang Mo Kio Ave 3 #01-1810, Singapore 560122",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-awwa-bedok",
    name: "AWWA AAC (Bedok)",
    lat: 1.3236,
    lng: 103.9301,
    category: "Active Ageing Centre",
    description:
      "Operated by AWWA. Programs include Tai Chi, social activities, befriending and digital literacy support for seniors aged 60+.",
    address: "Blk 16 Bedok South Road #01-625, Singapore 460016",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-awwa-punggol",
    name: "AWWA AAC (Punggol)",
    lat: 1.3935,
    lng: 103.9115,
    category: "Active Ageing Centre",
    description:
      "Operated by AWWA. Programs include exercises, social activities, buddying services and community outreach for seniors aged 60+.",
    address: "Blk 126A Edgedale Plains #01-01, Singapore 821126",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-awwa-yishun-762",
    name: "AWWA AAC (Yishun 762)",
    lat: 1.434,
    lng: 103.8285,
    category: "Active Ageing Centre",
    description:
      "Operated by AWWA. Programs include strength training, social activities, health screening and community support for seniors aged 60+.",
    address: "Blk 762 Yishun St 72 #01-324, Singapore 760762",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-brahm-centre-macpherson",
    name: "Brahm Centre AAC (MacPherson)",
    lat: 1.3254,
    lng: 103.8824,
    category: "Active Ageing Centre",
    description:
      "Operated by Brahm Centre. Programs include mindfulness exercises, social activities, health monitoring and community support for seniors aged 60+.",
    address: "Blk 61 Circuit Road #01-306, Singapore 370061",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-brahm-centre-simei",
    name: "Brahm Centre AAC (Simei)",
    lat: 1.342,
    lng: 103.9537,
    category: "Active Ageing Centre",
    description:
      "Operated by Brahm Centre. Programs include exercises, social activities, befriending, digital literacy workshops and community support for seniors aged 60+.",
    address: "Blk 248 Simei St 3 #01-128, Singapore 520248",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-brahm-centre-tampines",
    name: "Brahm Centre AAC (Tampines)",
    lat: 1.359,
    lng: 103.954,
    category: "Active Ageing Centre",
    description:
      "Operated by Brahm Centre. Programs include Tai Chi, social activities, befriending and health screening for seniors aged 60+.",
    address: "Blk 808 Tampines Ave 4 #01-191, Singapore 520808",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-calvary-community-care-macpherson",
    name: "Calvary AAC (MacPherson)",
    lat: 1.3268,
    lng: 103.882,
    category: "Active Ageing Centre",
    description:
      "Operated by Calvary Community Care. Programs include exercises, social activities, befriending and community support for seniors aged 60+.",
    address: "Blk 89 Circuit Road #01-140, Singapore 370089",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-calvary-community-care-paya-lebar",
    name: "Calvary AAC (Paya Lebar)",
    lat: 1.3282,
    lng: 103.8932,
    category: "Active Ageing Centre",
    description:
      "Operated by Calvary Community Care. Programs include exercise programmes, social activities, health screening and outreach support for seniors aged 60+.",
    address: "Blk 51 Ubi Ave 1 #01-08, Singapore 400051",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-care-corner-admiralty",
    name: "Care Corner AAC (Admiralty)",
    lat: 1.44,
    lng: 103.7892,
    category: "Active Ageing Centre",
    description:
      "Operated by Care Corner. Programs include exercise classes, social activities, befriending, digital literacy and community support for seniors aged 60+.",
    address: "Blk 691 Woodlands Drive 73 #01-03, Singapore 730691",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-care-corner-care-toa-payoh-79",
    name: "Care Corner AAC (Care) (Toa Payoh 79)",
    lat: 1.3338,
    lng: 103.8481,
    category: "Active Ageing Centre",
    description:
      "Operated by Care Corner. Programs include exercises, social activities, befriending and integrated day care or rehabilitation support for seniors aged 60+.",
    address: "Blk 79 Toa Payoh Lorong 4 #01-47, Singapore 310079",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-care-corner-marsiling",
    name: "Care Corner AAC (Marsiling)",
    lat: 1.4374,
    lng: 103.7738,
    category: "Active Ageing Centre",
    description:
      "Operated by Care Corner. Programs include exercise programmes, social activities, buddying services and community outreach for seniors aged 60+.",
    address: "Blk 205 Marsiling Drive #01-315, Singapore 730205",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-care-corner-teck-whye",
    name: "Care Corner AAC (Teck Whye)",
    lat: 1.3832,
    lng: 103.7554,
    category: "Active Ageing Centre",
    description:
      "Operated by Care Corner. Programs include Zumba, social activities, befriending and health monitoring for seniors aged 60+.",
    address: "Blk 19 Teck Whye Lane #01-196, Singapore 680019",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-care-corner-toa-payoh-5",
    name: "Care Corner AAC (Toa Payoh 5)",
    lat: 1.3335,
    lng: 103.8444,
    category: "Active Ageing Centre",
    description:
      "Operated by Care Corner. Programs include exercises, social activities, befriending and community support for seniors aged 60+.",
    address: "Blk 5 Lorong 7 Toa Payoh #01-131, Singapore 310005",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-care-corner-toa-payoh-62b",
    name: "Care Corner AAC (Toa Payoh 62B)",
    lat: 1.3381,
    lng: 103.8507,
    category: "Active Ageing Centre",
    description:
      "Operated by Care Corner. Programs include Tai Chi, social activities, befriending and health screening for seniors aged 60+.",
    address: "Blk 62B Lorong 4 Toa Payoh #02-121, Singapore 312062",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-care-corner-woodlands",
    name: "Care Corner AAC (Woodlands)",
    lat: 1.4394,
    lng: 103.7789,
    category: "Active Ageing Centre",
    description:
      "Operated by Care Corner. Programs include exercise programmes, social activities, digital literacy and buddying support for seniors aged 60+.",
    address: "Blk 762 Woodlands Circle #01-367, Singapore 730762",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-care-corner-woodlands-305",
    name: "Care Corner AAC (Woodlands 305)",
    lat: 1.435,
    lng: 103.773,
    category: "Active Ageing Centre",
    description:
      "Operated by Care Corner. Programs include exercise sessions, social activities, befriending and community support for seniors aged 60+.",
    address: "Blk 305 Woodlands St 31 #02-241, Singapore 730305",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-fei-yue-bukit-batok",
    name: "Fei Yue AAC (Bukit Batok)",
    lat: 1.354,
    lng: 103.7444,
    category: "Active Ageing Centre",
    description:
      "Operated by Fei Yue Community Services. Programs include exercises, social activities, befriending, health screening and community support for seniors aged 60+.",
    address: "Blk 182 Bukit Batok West Ave 8 #01-292, Singapore 650182",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-fei-yue-bukit-panjang",
    name: "Fei Yue AAC (Bukit Panjang)",
    lat: 1.3798,
    lng: 103.7723,
    category: "Active Ageing Centre",
    description:
      "Operated by Fei Yue Community Services. Programs include exercise programmes, social activities, buddying and community outreach for seniors aged 60+.",
    address: "Blk 256 Bukit Panjang Ring Road #01-60, Singapore 670256",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-fei-yue-choa-chu-kang",
    name: "Fei Yue AAC (Choa Chu Kang)",
    lat: 1.3854,
    lng: 103.7431,
    category: "Active Ageing Centre",
    description:
      "Operated by Fei Yue Community Services. Programs include Zumba and Tai Chi, social activities, befriending and health monitoring for seniors aged 60+.",
    address: "Blk 301 Choa Chu Kang Ave 4 #01-11, Singapore 680301",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-fei-yue-sembawang",
    name: "Fei Yue AAC (Sembawang)",
    lat: 1.4485,
    lng: 103.8199,
    category: "Active Ageing Centre",
    description:
      "Operated by Fei Yue Community Services. Programs include exercise classes, social activities, digital literacy and outreach support for seniors aged 60+.",
    address: "Blk 312 Sembawang Vista #01-41, Singapore 750312",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-fei-yue-woodlands-604",
    name: "Fei Yue AAC (Woodlands 604)",
    lat: 1.431,
    lng: 103.7817,
    category: "Active Ageing Centre",
    description:
      "Operated by Fei Yue Community Services. Programs include exercises, social activities, befriending and community support for seniors aged 60+.",
    address: "Blk 604 Woodlands Drive 42 #01-36, Singapore 730604",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-fei-yue-woodlands-688",
    name: "Fei Yue AAC (Woodlands 688)",
    lat: 1.437,
    lng: 103.7907,
    category: "Active Ageing Centre",
    description:
      "Operated by Fei Yue Community Services. Programs include exercise programmes, social activities, buddying services and health screening for seniors aged 60+.",
    address: "Blk 688B Woodlands Drive 75 #02-01, Singapore 732688",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-fei-yue-woodlands-883",
    name: "Fei Yue AAC (Woodlands 883)",
    lat: 1.4408,
    lng: 103.7808,
    category: "Active Ageing Centre",
    description:
      "Operated by Fei Yue Community Services. Programs include strength training, social activities, befriending and community support for seniors aged 60+.",
    address: "Blk 883 Woodlands St 82 #01-470, Singapore 730883",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-fei-yue-yew-tee",
    name: "Fei Yue AAC (Yew Tee)",
    lat: 1.397,
    lng: 103.747,
    category: "Active Ageing Centre",
    description:
      "Operated by Fei Yue Community Services. Programs include exercises, social activities, digital literacy workshops and community outreach for seniors aged 60+.",
    address: "Blk 608 Choa Chu Kang St 62 #01-28, Singapore 680608",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-filos-jalan-besar",
    name: "Filos AAC (Jalan Besar)",
    lat: 1.306,
    lng: 103.86,
    category: "Active Ageing Centre",
    description:
      "Operated by Filos Community Services. Programs include exercises, social activities, befriending and community support for seniors aged 60+.",
    address: "Blk 809 French Road #01-30, Singapore 200809",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-filos-kampung-glam",
    name: "Filos AAC (Kampung Glam)",
    lat: 1.3005,
    lng: 103.8591,
    category: "Active Ageing Centre",
    description:
      "Operated by Filos Community Services. Programs include exercise sessions, social activities, buddying services and community support for seniors aged 60+.",
    address: "Blk 4 Beach Road #01-33, Singapore 190004",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-goodlife-by-fei-yue-bukit-panjang",
    name: "Goodlife! AAC (Bukit Panjang)",
    lat: 1.382,
    lng: 103.7612,
    category: "Active Ageing Centre",
    description:
      "Operated by Goodlife! by Fei Yue. Programs include exercises, social activities, digital literacy, health monitoring and community support for seniors aged 60+.",
    address: "Blk 547 Segar Road #01-01, Singapore 670547",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-goodlife-by-fei-yue-woodlands",
    name: "Goodlife! AAC (Woodlands)",
    lat: 1.4416,
    lng: 103.7872,
    category: "Active Ageing Centre",
    description:
      "Operated by Goodlife! by Fei Yue. Programs include exercise programmes, social activities, befriending and outreach support for seniors aged 60+.",
    address: "Blk 888 Woodlands Drive 50 #01-749, Singapore 730888",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-goodlife-metta-simei",
    name: "GoodLife! Metta AAC (Simei)",
    lat: 1.3435,
    lng: 103.953,
    category: "Active Ageing Centre",
    description:
      "Operated by GoodLife! Metta. Programs include exercises, social activities, befriending, health screening and community support for seniors aged 60+.",
    address: "Blk 5 Simei St 3 #01-198, Singapore 529893",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-henderson-home",
    name: "Henderson Home AAC",
    lat: 1.287,
    lng: 103.8183,
    category: "Active Ageing Centre",
    description:
      "Operated by Henderson Home. Programs include exercises, social activities, befriending, health screening and community support for seniors aged 60+.",
    address: "Blk 130 Bukit Merah View #06-301, Singapore 151130",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-kampong-kapor-community-services",
    name: "Kampong Kapor Community Services AAC",
    lat: 1.3082,
    lng: 103.857,
    category: "Active Ageing Centre",
    description:
      "Operated by Kampong Kapor Community Services. Programs include exercise programmes, social activities, buddying services and community outreach for seniors aged 60+.",
    address: "Blk 4 Jalan Kledek #01-01, Singapore 199264",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-lions-befrienders-bukit-merah",
    name: "Lions Befrienders AAC (Bukit Merah)",
    lat: 1.287,
    lng: 103.8178,
    category: "Active Ageing Centre",
    description:
      "Operated by Lions Befrienders. Programs include exercises, social activities, befriending, health screening and community support for seniors aged 60+.",
    address: "Blk 130 Bukit Merah View #01-358, Singapore 150130",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-lions-befrienders-bukit-merah-central",
    name: "Lions Befrienders AAC (Bukit Merah Central)",
    lat: 1.2834,
    lng: 103.8141,
    category: "Active Ageing Centre",
    description:
      "Operated by Lions Befrienders. Programs include exercise sessions, social activities, buddying and outreach support for seniors aged 60+.",
    address: "Blk 119 Bukit Merah Lane 1 #01-58, Singapore 150119",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-lions-befrienders-clementi",
    name: "Lions Befrienders AAC (Clementi)",
    lat: 1.3108,
    lng: 103.7646,
    category: "Active Ageing Centre",
    description:
      "Operated by Lions Befrienders. Programs include Tai Chi, social activities, befriending and health monitoring for seniors aged 60+.",
    address: "Blk 333 Clementi Ave 2 #01-188, Singapore 120333",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-lions-befrienders-ghim-moh",
    name: "Lions Befrienders AAC (Ghim Moh)",
    lat: 1.312,
    lng: 103.7887,
    category: "Active Ageing Centre",
    description:
      "Operated by Lions Befrienders. Programs include exercise programmes, social activities, digital literacy and community support for seniors aged 60+.",
    address: "Blk 9 Ghim Moh Road #01-25, Singapore 270009",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-lions-befrienders-henderson",
    name: "Lions Befrienders AAC (Henderson)",
    lat: 1.282,
    lng: 103.8181,
    category: "Active Ageing Centre",
    description:
      "Operated by Lions Befrienders. Programs include exercises, social activities, befriending and community support for seniors aged 60+.",
    address: "Blk 115A Jalan Bukit Merah #01-21, Singapore 162115",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-lions-befrienders-lengkok-bahru",
    name: "Lions Befrienders AAC (Lengkok Bahru)",
    lat: 1.2851,
    lng: 103.823,
    category: "Active Ageing Centre",
    description:
      "Operated by Lions Befrienders. Programs include exercise classes, social activities, buddying services and outreach support for seniors aged 60+.",
    address: "Blk 57 Lengkok Bahru #01-481, Singapore 150057",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-lions-befrienders-mei-ling",
    name: "Lions Befrienders AAC (Mei Ling)",
    lat: 1.2932,
    lng: 103.8012,
    category: "Active Ageing Centre",
    description:
      "Operated by Lions Befrienders. Programs include exercises, social activities, health screening and community support for seniors aged 60+.",
    address: "Blk 158 Mei Ling Street #01-67, Singapore 140158",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-lions-befrienders-redhill",
    name: "Lions Befrienders AAC (Redhill)",
    lat: 1.2877,
    lng: 103.8176,
    category: "Active Ageing Centre",
    description:
      "Operated by Lions Befrienders. Programs include Zumba and low-impact training, social activities and befriending support for seniors aged 60+.",
    address: "Blk 85 Redhill Close #01-538, Singapore 150085",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-lions-befrienders-telok-blangah",
    name: "Lions Befrienders AAC (Telok Blangah)",
    lat: 1.272,
    lng: 103.8172,
    category: "Active Ageing Centre",
    description:
      "Operated by Lions Befrienders. Programs include exercises, social activities, digital literacy and community outreach for seniors aged 60+.",
    address: "Blk 3 Telok Blangah Crescent #01-73, Singapore 090003",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-lions-befrienders-toa-payoh",
    name: "Lions Befrienders AAC (Toa Payoh)",
    lat: 1.3337,
    lng: 103.8442,
    category: "Active Ageing Centre",
    description:
      "Operated by Lions Befrienders. Programs include exercises, social activities, buddying services and community support for seniors aged 60+.",
    address: "Blk 5A Toa Payoh Lorong 7 #01-104, Singapore 311005",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-methodist-welfare-services-charis-ace-geylang-east",
    name: "MWS Charis ACE AAC (Geylang East)",
    lat: 1.3173,
    lng: 103.885,
    category: "Active Ageing Centre",
    description:
      "Operated by Methodist Welfare Services. Programs include exercises, social activities, health screening, befriending and community support for seniors aged 60+.",
    address: "Blk 125 Geylang East Ave 1 #01-05, Singapore 381125",
    hours: "Mon–Fri 9AM–5PM (closed weekends & PH)",
  },
  {
    id: "aac-methodist-welfare-services-fernvale-rivergrove",
    name: "MWS AAC (Fernvale Rivergrove)",
    lat: 1.392,
    lng: 103.876,
    category: "Active Ageing Centre",
    description:
      "Operated by Methodist Welfare Services. Programs include exercise programmes, social activities, buddying and digital literacy support for seniors aged 60+.",
    address: "Blk 473A Fernvale Street #01-17, Singapore 791473",
    hours: "Mon–Fri 9AM–5PM (closed weekends & PH)",
  },
  {
    id: "aac-methodist-welfare-services-golden-lily-pasir-ris",
    name: "MWS AAC (Golden Lily@Pasir Ris)",
    lat: 1.372,
    lng: 103.9618,
    category: "Active Ageing Centre",
    description:
      "Operated by Methodist Welfare Services. Programs include exercises, social activities, health monitoring and community outreach for seniors aged 60+.",
    address: "Blk 212A Pasir Ris St 21 #01-616, Singapore 511212",
    hours: "Mon–Fri 9AM–5PM (closed weekends & PH)",
  },
  {
    id: "aac-methodist-welfare-services-greentops-sims-place",
    name: "MWS AAC (GreenTops@Sims Place)",
    lat: 1.3128,
    lng: 103.8735,
    category: "Active Ageing Centre",
    description:
      "Operated by Methodist Welfare Services. Programs include Tai Chi, social activities, befriending and community support for seniors aged 60+.",
    address: "Blk 63 Sims Place #01-227, Singapore 380063",
    hours: "Mon–Fri 9AM–5PM (closed weekends & PH)",
  },
  {
    id: "aac-methodist-welfare-services-kebun-baru",
    name: "MWS AAC (Kebun Baru)",
    lat: 1.3662,
    lng: 103.8488,
    category: "Active Ageing Centre",
    description:
      "Operated by Methodist Welfare Services. Programs include exercise sessions, social activities, health screening and outreach support for seniors aged 60+.",
    address: "Blk 180 Ang Mo Kio Ave 5 #01-2980, Singapore 560180",
    hours: "Mon–Fri 9AM–5PM (closed weekends & PH)",
  },
  {
    id: "aac-methodist-welfare-services-teck-ghee-vista",
    name: "MWS AAC (Teck Ghee Vista)",
    lat: 1.3736,
    lng: 103.84,
    category: "Active Ageing Centre",
    description:
      "Operated by Methodist Welfare Services. Programs include exercise programmes, social activities, buddying and community support for seniors aged 60+.",
    address: "Blk 307D Ang Mo Kio Ave 1 #01-01, Singapore 564307",
    hours: "Mon–Fri 9AM–5PM (closed weekends & PH)",
  },
  {
    id: "aac-methodist-welfare-services-wesley-jalan-berseh",
    name: "MWS Wesley AAC (Jalan Berseh)",
    lat: 1.3065,
    lng: 103.856,
    category: "Active Ageing Centre",
    description:
      "Operated by Methodist Welfare Services. Programs include exercises, social activities, digital literacy workshops and community support for seniors aged 60+.",
    address: "Blk 25 Jalan Berseh #01-142, Singapore 200025",
    hours: "Mon–Fri 9AM–5PM (closed weekends & PH)",
  },
  {
    id: "aac-montfort-care-geylang-bahru",
    name: "Montfort Care AAC (Geylang Bahru)",
    lat: 1.3148,
    lng: 103.8685,
    category: "Active Ageing Centre",
    description:
      "Operated by Montfort Care. Programs include exercise classes, social activities, befriending and health screening for seniors aged 60+.",
    address: "Blk 63 Kallang Bahru #01-433, Singapore 330063",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-montfort-care-hougang-681",
    name: "Montfort Care AAC (Hougang 681)",
    lat: 1.375,
    lng: 103.889,
    category: "Active Ageing Centre",
    description:
      "Operated by Montfort Care. Programs include exercises, social activities, buddying services and community support for seniors aged 60+.",
    address: "Blk 681 Hougang Ave 8 #01-831, Singapore 530681",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-montfort-care-macpherson",
    name: "Montfort Care AAC (MacPherson)",
    lat: 1.3265,
    lng: 103.8828,
    category: "Active Ageing Centre",
    description:
      "Operated by Montfort Care. Programs include exercise programmes, social activities, befriending and outreach support for seniors aged 60+.",
    address: "Blk 53 Circuit Road #01-45, Singapore 370053",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-montfort-care-punggol",
    name: "Montfort Care AAC (Punggol)",
    lat: 1.3987,
    lng: 103.9078,
    category: "Active Ageing Centre",
    description:
      "Operated by Montfort Care. Programs include exercises, social activities, health monitoring and community support for seniors aged 60+.",
    address: "Blk 168B Punggol Field #01-01, Singapore 822168",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-montfort-care-serangoon-north",
    name: "Montfort Care AAC (Serangoon North)",
    lat: 1.371,
    lng: 103.8458,
    category: "Active Ageing Centre",
    description:
      "Operated by Montfort Care. Programs include strength training, social activities, befriending and community outreach for seniors aged 60+.",
    address: "Blk 159 Ang Mo Kio Ave 5 #01-286, Singapore 560159",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-ntuc-health-boon-lay",
    name: "NTUC Health AAC (Boon Lay)",
    lat: 1.3464,
    lng: 103.7055,
    category: "Active Ageing Centre",
    description:
      "Operated by NTUC Health. Programs include exercises, social activities, befriending, health screening and community support for seniors aged 60+.",
    address: "179 Boon Lay Drive #01-448, Singapore 640179",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-ntuc-health-bukit-batok-west-care",
    name: "NTUC Health AAC (Care) (Bukit Batok West)",
    lat: 1.3504,
    lng: 103.7418,
    category: "Active Ageing Centre",
    description:
      "Operated by NTUC Health. Programs include exercises, social activities, befriending and integrated day care or rehabilitation support for seniors aged 60+.",
    address: "Blk 439 Bukit Batok West Ave 8 #02-01, Singapore 650439",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-ntuc-health-bukit-merah",
    name: "NTUC Health AAC (Bukit Merah)",
    lat: 1.2836,
    lng: 103.8179,
    category: "Active Ageing Centre",
    description:
      "Operated by NTUC Health. Programs include exercise programmes, social activities, buddying and community support for seniors aged 60+.",
    address: "117 Jalan Bukit Merah #01-1683, Singapore 160117",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-ntuc-health-bukit-merah-silat-care",
    name: "NTUC Health AAC (Care) (Bukit Merah Silat)",
    lat: 1.282,
    lng: 103.8262,
    category: "Active Ageing Centre",
    description:
      "Operated by NTUC Health. Programs include exercise classes, social activities, befriending and day care or rehabilitation services for seniors aged 60+.",
    address: "Blk 145 Jalan Bukit Merah #01-1094, Singapore 160145",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-ntuc-health-bukit-merah-view",
    name: "NTUC Health AAC (Bukit Merah View)",
    lat: 1.2865,
    lng: 103.8155,
    category: "Active Ageing Centre",
    description:
      "Operated by NTUC Health. Programs include exercises, social activities, health screening and community outreach for seniors aged 60+.",
    address: "117 Bukit Merah View #01-205, Singapore 151117",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-ntuc-health-bukit-panjang",
    name: "NTUC Health AAC (Bukit Panjang)",
    lat: 1.3799,
    lng: 103.7645,
    category: "Active Ageing Centre",
    description:
      "Operated by NTUC Health. Programs include Zumba and Tai Chi, social activities, befriending and support for seniors aged 60+.",
    address: "2 Bukit Panjang Ring Road #02-06, Singapore 679947",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-ntuc-health-chai-chee",
    name: "NTUC Health AAC (Chai Chee)",
    lat: 1.3231,
    lng: 103.9215,
    category: "Active Ageing Centre",
    description:
      "Operated by NTUC Health. Programs include exercises, social activities, digital literacy workshops and community support for seniors aged 60+.",
    address: "Blk 28 New Upper Changi Road #01-666, Singapore 461028",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-ntuc-health-eunos-crescent",
    name: "NTUC Health AAC (Eunos Crescent)",
    lat: 1.3195,
    lng: 103.9033,
    category: "Active Ageing Centre",
    description:
      "Operated by NTUC Health. Programs include exercise programmes, social activities, buddying services and health monitoring for seniors aged 60+.",
    address: "Blk 4A Eunos Crescent #01-2602, Singapore 401004",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-ntuc-health-heartbeat-bedok-care",
    name: "NTUC Health AAC (Care) (Heartbeat@Bedok)",
    lat: 1.327,
    lng: 103.9334,
    category: "Active Ageing Centre",
    description:
      "Operated by NTUC Health. Programs include exercises, social activities, hot meals, befriending and day care or rehabilitation support for seniors aged 60+.",
    address: "11 Bedok North Street 1 #02-02, Singapore 469662",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-ntuc-health-henderson",
    name: "NTUC Health AAC (Henderson)",
    lat: 1.2858,
    lng: 103.8203,
    category: "Active Ageing Centre",
    description:
      "Operated by NTUC Health. Programs include exercises, social activities, befriending and outreach support for seniors aged 60+.",
    address: "Blk 95 Henderson Road #01-206, Singapore 150095",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-ntuc-health-jurong-central-care",
    name: "NTUC Health AAC (Care) (Jurong Central)",
    lat: 1.336,
    lng: 103.7281,
    category: "Active Ageing Centre",
    description:
      "Operated by NTUC Health. Programs include strength training, social activities, befriending and day care or rehabilitation services for seniors aged 60+.",
    address: "3 Yung Sheng Road #01-01, Singapore 618497",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-ntuc-health-jurong-west",
    name: "NTUC Health AAC (Jurong West)",
    lat: 1.35,
    lng: 103.7195,
    category: "Active Ageing Centre",
    description:
      "Operated by NTUC Health. Programs include exercise programmes, social activities, digital literacy and community support for seniors aged 60+.",
    address: "Blk 517 Jurong West St 52 #01-353, Singapore 640517",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-ntuc-health-kampung-admiralty-care",
    name: "NTUC Health AAC (Care) (Kampung Admiralty)",
    lat: 1.4407,
    lng: 103.8006,
    category: "Active Ageing Centre",
    description:
      "Operated by NTUC Health. Programs include exercises, social activities, hot meal services, befriending and day care support for seniors aged 60+.",
    address: "676 Woodlands Drive 71 #01-01, Singapore 730676",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-ntuc-health-marine-parade",
    name: "NTUC Health AAC (Marine Parade)",
    lat: 1.3045,
    lng: 103.9113,
    category: "Active Ageing Centre",
    description:
      "Operated by NTUC Health. Programs include exercises, social activities, health screening and community support for seniors aged 60+.",
    address: "Blk 50 Marine Crescent #01-768, Singapore 440050",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-ntuc-health-marsiling",
    name: "NTUC Health AAC (Marsiling)",
    lat: 1.438,
    lng: 103.7752,
    category: "Active Ageing Centre",
    description:
      "Operated by NTUC Health. Programs include exercise sessions, social activities, befriending and community outreach for seniors aged 60+.",
    address: "Blk 213 Marsiling Crescent #01-198, Singapore 730213",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-ntuc-health-pasir-ris",
    name: "NTUC Health AAC (Pasir Ris)",
    lat: 1.3736,
    lng: 103.953,
    category: "Active Ageing Centre",
    description:
      "Operated by NTUC Health. Programs include Tai Chi, social activities, buddying services and health monitoring for seniors aged 60+.",
    address: "Blk 576 Pasir Ris St 53 #01-78, Singapore 510576",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-ntuc-health-pioneer",
    name: "NTUC Health AAC (Pioneer)",
    lat: 1.3376,
    lng: 103.6981,
    category: "Active Ageing Centre",
    description:
      "Operated by NTUC Health. Programs include exercises, social activities, befriending and digital literacy support for seniors aged 60+.",
    address: "Blk 670 Jurong West St 64 #01-260, Singapore 640670",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-ntuc-health-queenstown",
    name: "NTUC Health AAC (Queenstown)",
    lat: 1.2975,
    lng: 103.7983,
    category: "Active Ageing Centre",
    description:
      "Operated by NTUC Health. Programs include exercise programmes, social activities, befriending and community support for seniors aged 60+.",
    address: "Blk 53 Strathmore Ave #01-220, Singapore 141053",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-ntuc-health-taman-jurong-care",
    name: "NTUC Health AAC (Care) (Taman Jurong)",
    lat: 1.3357,
    lng: 103.729,
    category: "Active Ageing Centre",
    description:
      "Operated by NTUC Health. Programs include exercises, social activities, befriending and integrated day care or rehabilitation support for seniors aged 60+.",
    address: "310 Jurong East St 32 #01-118, Singapore 600310",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-ntuc-health-tampines",
    name: "NTUC Health AAC (Tampines)",
    lat: 1.353,
    lng: 103.9438,
    category: "Active Ageing Centre",
    description:
      "Operated by NTUC Health. Programs include exercises, social activities, health screening and community support for seniors aged 60+.",
    address: "Blk 122 Tampines St 11 #01-207, Singapore 521122",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-ntuc-health-telok-blangah",
    name: "NTUC Health AAC (Telok Blangah)",
    lat: 1.2726,
    lng: 103.8078,
    category: "Active Ageing Centre",
    description:
      "Operated by NTUC Health. Programs include exercise classes, social activities, buddying services and outreach support for seniors aged 60+.",
    address: "Blk 79 Telok Blangah Drive #01-510, Singapore 100079",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-ntuc-health-toa-payoh",
    name: "NTUC Health AAC (Toa Payoh)",
    lat: 1.3358,
    lng: 103.8468,
    category: "Active Ageing Centre",
    description:
      "Operated by NTUC Health. Programs include exercise programmes, social activities, digital literacy workshops and community support for seniors aged 60+.",
    address: "Blk 73 Toa Payoh Lorong 4 #01-137, Singapore 310073",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-ntuc-health-whampoa",
    name: "NTUC Health AAC (Whampoa)",
    lat: 1.3229,
    lng: 103.855,
    category: "Active Ageing Centre",
    description:
      "Operated by NTUC Health. Programs include exercises, social activities, befriending and health screening for seniors aged 60+.",
    address: "Blk 85 Whampoa Drive #01-854, Singapore 320085",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-ntuc-health-woodlands",
    name: "NTUC Health AAC (Woodlands)",
    lat: 1.4381,
    lng: 103.7858,
    category: "Active Ageing Centre",
    description:
      "Operated by NTUC Health. Programs include exercises, social activities, befriending and community outreach for seniors aged 60+.",
    address: "Blk 686A Woodlands Drive 73 #02-01, Singapore 731686",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-ntuc-health-yishun",
    name: "NTUC Health AAC (Yishun)",
    lat: 1.429,
    lng: 103.8356,
    category: "Active Ageing Centre",
    description:
      "Operated by NTUC Health. Programs include exercises, social activities, health screening, befriending and support for seniors aged 60+.",
    address: "Blk 747 Yishun Ave 6 #01-A01, Singapore 760747",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-pcs-jalan-bukit-merah",
    name: "PCS Cedar Tree AAC (Jalan Bukit Merah)",
    lat: 1.2841,
    lng: 103.8179,
    category: "Active Ageing Centre",
    description:
      "Operated by Presbyterian Community Services. Programs include exercises, social activities, befriending and community support for seniors aged 60+.",
    address: "Blk 105 Jalan Bukit Merah #02-1912, Singapore 160105",
    hours: "Mon–Fri 8:30AM–6PM",
  },
  {
    id: "aac-pcs-care-potong-pasir-108",
    name: "PCS Cedar Tree AAC (Care) (Potong Pasir 108)",
    lat: 1.3317,
    lng: 103.8672,
    category: "Active Ageing Centre",
    description:
      "Operated by Presbyterian Community Services. Programs include exercises, social activities, befriending and day care or rehabilitation support for seniors aged 60+.",
    address: "Blk 108 Potong Pasir Ave 1 #01-488, Singapore 350108",
    hours: "Mon–Fri 8:30AM–6PM",
  },
  {
    id: "aac-pcs-strathmore-61",
    name: "PCS Cedar Tree AAC (Strathmore 61)",
    lat: 1.2972,
    lng: 103.7994,
    category: "Active Ageing Centre",
    description:
      "Operated by Presbyterian Community Services. Programs include exercise programmes, social activities, buddying and health screening for seniors aged 60+.",
    address: "Blk 61 Strathmore Ave #01-02, Singapore 141061",
    hours: "Mon–Fri 8:30AM–6PM",
  },
  {
    id: "aac-pcs-tampines-west-827a",
    name: "PCS Cedar Tree AAC (Tampines West 827A)",
    lat: 1.3518,
    lng: 103.9405,
    category: "Active Ageing Centre",
    description:
      "Operated by Presbyterian Community Services. Programs include exercises, social activities, digital literacy and community support for seniors aged 60+.",
    address: "Blk 827A Tampines St 81 #02-350, Singapore 521827",
    hours: "Mon–Fri 8:30AM–6PM",
  },
  {
    id: "aac-pcs-toh-yi-21",
    name: "PCS Cedar Tree AAC (Toh Yi 21)",
    lat: 1.3368,
    lng: 103.7748,
    category: "Active Ageing Centre",
    description:
      "Operated by Presbyterian Community Services. Programs include exercise classes, social activities, befriending and outreach support for seniors aged 60+.",
    address: "Blk 21 Toh Yi Drive #02-601, Singapore 590021",
    hours: "Mon–Fri 8:30AM–6PM",
  },
  {
    id: "aac-pcs-upper-serangoon-364",
    name: "PCS Cedar Tree AAC (Upper Serangoon 364)",
    lat: 1.358,
    lng: 103.8745,
    category: "Active Ageing Centre",
    description:
      "Operated by Presbyterian Community Services. Programs include exercises, social activities, buddying services and community support for seniors aged 60+.",
    address: "Blk 364 Upper Serangoon Road #01-01, Singapore 530364",
    hours: "Mon–Fri 8:30AM–6PM",
  },
  {
    id: "aac-reach-bukit-batok",
    name: "REACH AAC (Bukit Batok)",
    lat: 1.349,
    lng: 103.7497,
    category: "Active Ageing Centre",
    description:
      "Operated by REACH Community Services. Programs include exercises, social activities, befriending and community support for seniors aged 60+.",
    address: "Blk 334 Bukit Batok St 32 #01-01, Singapore 650334",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-reach-jurong-west-729",
    name: "REACH AAC (Jurong West 729)",
    lat: 1.3534,
    lng: 103.716,
    category: "Active Ageing Centre",
    description:
      "Operated by REACH Community Services. Programs include exercise programmes, social activities, health screening and outreach support for seniors aged 60+.",
    address: "Blk 729 Jurong West Ave 5 #01-210, Singapore 640729",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-sage-jurong-east",
    name: "SAGE AAC (Jurong East)",
    lat: 1.3338,
    lng: 103.7359,
    category: "Active Ageing Centre",
    description:
      "Operated by SAGE Counselling Centre. Programs include exercises, social activities, befriending, health screening and community support for seniors aged 60+.",
    address: "Blk 304 Jurong East St 32 #01-05, Singapore 600304",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-sasco-kim-tian",
    name: "SASCO AAC (Kim Tian)",
    lat: 1.2857,
    lng: 103.8118,
    category: "Active Ageing Centre",
    description:
      "Operated by SASCO. Programs include exercise programmes, social activities, buddying and community support for seniors aged 60+.",
    address: "Blk 161 Bukit Merah Central #01-3731, Singapore 150161",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-silverace-punggol",
    name: "SilverACE AAC (Punggol)",
    lat: 1.401,
    lng: 103.9094,
    category: "Active Ageing Centre",
    description:
      "Operated by SilverACE. Programs include exercises, social activities, digital literacy workshops and community support for seniors aged 60+.",
    address: "Blk 668B Punggol Drive #01-01, Singapore 822668",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-silverace-sengkang",
    name: "SilverACE AAC (Sengkang)",
    lat: 1.391,
    lng: 103.8975,
    category: "Active Ageing Centre",
    description:
      "Operated by SilverACE. Programs include exercises, social activities, befriending and health monitoring for seniors aged 60+.",
    address: "Blk 261 Sengkang East Way #01-01, Singapore 541261",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-st-lukes-eldercare-ang-mo-kio",
    name: "St Luke's ElderCare AAC (Ang Mo Kio)",
    lat: 1.3688,
    lng: 103.852,
    category: "Active Ageing Centre",
    description:
      "Operated by St Luke's ElderCare. Programs include exercises, social activities, health screening and community support for seniors aged 60+.",
    address: "Blk 261 Ang Mo Kio Ave 3 #01-01, Singapore 560261",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-st-lukes-eldercare-bishan",
    name: "St Luke's ElderCare AAC (Bishan)",
    lat: 1.3505,
    lng: 103.8522,
    category: "Active Ageing Centre",
    description:
      "Operated by St Luke's ElderCare. Programs include exercise programmes, social activities, buddying and community support for seniors aged 60+.",
    address: "Blk 197 Bishan St 13 #01-560, Singapore 570197",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-st-lukes-eldercare-bukit-batok",
    name: "St Luke's ElderCare AAC (Bukit Batok)",
    lat: 1.349,
    lng: 103.7497,
    category: "Active Ageing Centre",
    description:
      "Operated by St Luke's ElderCare. Programs include exercises, social activities, befriending and community outreach for seniors aged 60+.",
    address: "Blk 334 Bukit Batok St 32 #01-11, Singapore 650334",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-st-lukes-eldercare-care-hougang",
    name: "St Luke's ElderCare AAC (Care) (Hougang)",
    lat: 1.359,
    lng: 103.8856,
    category: "Active Ageing Centre",
    description:
      "Operated by St Luke's ElderCare. Programs include exercises, social activities, hot meals, befriending and day care or rehabilitation support for seniors aged 60+.",
    address: "Blk 207 Hougang St 21 #01-179, Singapore 530207",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-st-lukes-eldercare-hougang",
    name: "St Luke's ElderCare AAC (Hougang)",
    lat: 1.36,
    lng: 103.8842,
    category: "Active Ageing Centre",
    description:
      "Operated by St Luke's ElderCare. Programs include exercises, social activities, digital literacy and community support for seniors aged 60+.",
    address: "Blk 218 Hougang St 21 #01-243, Singapore 530218",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-st-lukes-eldercare-punggol",
    name: "St Luke's ElderCare AAC (Punggol)",
    lat: 1.3984,
    lng: 103.9062,
    category: "Active Ageing Centre",
    description:
      "Operated by St Luke's ElderCare. Programs include exercise programmes, social activities, buddying services and community outreach for seniors aged 60+.",
    address: "Blk 209 Punggol Place #02-01, Singapore 820209",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-st-lukes-eldercare-serangoon",
    name: "St Luke's ElderCare AAC (Serangoon)",
    lat: 1.369,
    lng: 103.871,
    category: "Active Ageing Centre",
    description:
      "Operated by St Luke's ElderCare. Programs include exercises, social activities, befriending and health monitoring for seniors aged 60+.",
    address: "Blk 110 Serangoon North Ave 2 #01-380, Singapore 550110",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-st-lukes-eldercare-whampoa",
    name: "St Luke's ElderCare AAC (Whampoa)",
    lat: 1.3265,
    lng: 103.853,
    category: "Active Ageing Centre",
    description:
      "Operated by St Luke's ElderCare. Programs include exercise classes, social activities, befriending and community support for seniors aged 60+.",
    address: "Blk 107 Jalan Rajah #01-270, Singapore 321107",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-tembusu-tampines",
    name: "Tembusu AAC (Tampines)",
    lat: 1.359,
    lng: 103.945,
    category: "Active Ageing Centre",
    description:
      "Operated by Tembusu. Programs include exercises, social activities, befriending, health screening and community support for seniors aged 60+.",
    address: "Blk 497E Tampines St 45 #01-01, Singapore 527497",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-thk-ang-mo-kio",
    name: "THK AAC (Ang Mo Kio)",
    lat: 1.368,
    lng: 103.8488,
    category: "Active Ageing Centre",
    description:
      "Operated by Thye Hua Kwan Moral Charities. Programs include exercise programmes, social activities, buddying and community support for seniors aged 60+.",
    address: "Blk 409 Ang Mo Kio Ave 10 #01-843, Singapore 560409",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-thk-bedok-reservoir",
    name: "THK AAC (Bedok Reservoir)",
    lat: 1.336,
    lng: 103.9266,
    category: "Active Ageing Centre",
    description:
      "Operated by Thye Hua Kwan Moral Charities. Programs include exercises, social activities, health screening and community support for seniors aged 60+.",
    address: "Blk 743 Bedok Reservoir Road #01-3007, Singapore 470743",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-thk-bukit-panjang",
    name: "THK AAC (Bukit Panjang)",
    lat: 1.383,
    lng: 103.7718,
    category: "Active Ageing Centre",
    description:
      "Operated by Thye Hua Kwan Moral Charities. Programs include Tai Chi, social activities, befriending and community outreach for seniors aged 60+.",
    address: "Blk 225 Bukit Panjang Ring Road #01-13, Singapore 670225",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-thk-hougang",
    name: "THK AAC (Hougang)",
    lat: 1.369,
    lng: 103.8851,
    category: "Active Ageing Centre",
    description:
      "Operated by Thye Hua Kwan Moral Charities. Programs include exercises, social activities, digital literacy workshops and community support for seniors aged 60+.",
    address: "Blk 613 Hougang Ave 8 #01-432, Singapore 530613",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-thk-jurong-spring",
    name: "THK AAC (Jurong Spring)",
    lat: 1.3505,
    lng: 103.7162,
    category: "Active Ageing Centre",
    description:
      "Operated by Thye Hua Kwan Moral Charities. Programs include exercise sessions, social activities, befriending and health monitoring for seniors aged 60+.",
    address: "Blk 537 Jurong West St 52 #01-282, Singapore 640537",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-thk-lengkok-bahru",
    name: "THK AAC (Lengkok Bahru)",
    lat: 1.2852,
    lng: 103.8215,
    category: "Active Ageing Centre",
    description:
      "Operated by Thye Hua Kwan Moral Charities. Programs include exercises, social activities, buddying services and outreach support for seniors aged 60+.",
    address: "Blk 60 Lengkok Bahru #01-355, Singapore 150060",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-thk-macpherson",
    name: "THK AAC (Macpherson)",
    lat: 1.3252,
    lng: 103.8821,
    category: "Active Ageing Centre",
    description:
      "Operated by Thye Hua Kwan Moral Charities. Programs include exercise programmes, social activities, befriending and community support for seniors aged 60+.",
    address: "Blk 76 Circuit Road #01-385, Singapore 370076",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-thk-queenstown",
    name: "THK AAC (Queenstown)",
    lat: 1.293,
    lng: 103.8025,
    category: "Active Ageing Centre",
    description:
      "Operated by Thye Hua Kwan Moral Charities. Programs include exercises, social activities, health screening and community support for seniors aged 60+.",
    address: "Blk 163 Stirling Road #01-1201, Singapore 140163",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-thk-tampines",
    name: "THK AAC (Tampines)",
    lat: 1.353,
    lng: 103.9525,
    category: "Active Ageing Centre",
    description:
      "Operated by Thye Hua Kwan Moral Charities. Programs include exercise classes, social activities, befriending and digital literacy support for seniors aged 60+.",
    address: "Blk 238 Tampines St 21 #01-18, Singapore 520238",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-thk-toa-payoh",
    name: "THK AAC (Toa Payoh)",
    lat: 1.341,
    lng: 103.853,
    category: "Active Ageing Centre",
    description:
      "Operated by Thye Hua Kwan Moral Charities. Programs include exercises, social activities, buddying services and community outreach for seniors aged 60+.",
    address: "Blk 230 Toa Payoh Lorong 8 #01-1006, Singapore 310230",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-thk-woodlands",
    name: "THK AAC (Woodlands)",
    lat: 1.441,
    lng: 103.7862,
    category: "Active Ageing Centre",
    description:
      "Operated by Thye Hua Kwan Moral Charities. Programs include exercises, social activities, health screening and community support for seniors aged 60+.",
    address: "Blk 669 Woodlands Ring Rd #01-1771, Singapore 730669",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-thk-yishun",
    name: "THK AAC (Yishun)",
    lat: 1.4316,
    lng: 103.8309,
    category: "Active Ageing Centre",
    description:
      "Operated by Thye Hua Kwan Moral Charities. Programs include exercise programmes, social activities, befriending and community support for seniors aged 60+.",
    address: "Blk 265 Yishun St 22 #01-125, Singapore 760265",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-touch-aljunied",
    name: "TOUCH AAC (Aljunied)",
    lat: 1.33,
    lng: 103.899,
    category: "Active Ageing Centre",
    description:
      "Operated by TOUCH Community Services. Programs include exercises, social activities, befriending and community support for seniors aged 60+.",
    address: "Blk 7 Lorong 7 Toa Payoh #01-31, Singapore 319654",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-touch-geylang-bahru",
    name: "TOUCH AAC (Geylang Bahru)",
    lat: 1.318,
    lng: 103.8645,
    category: "Active Ageing Centre",
    description:
      "Operated by TOUCH Community Services. Programs include exercise programmes, social activities, buddying services and outreach support for seniors aged 60+.",
    address: "Blk 58 Geylang Bahru #01-3505, Singapore 330058",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-tsao-foundation-whampoa",
    name: "Tsao Foundation AAC (Whampoa)",
    lat: 1.324,
    lng: 103.8558,
    category: "Active Ageing Centre",
    description:
      "Operated by Tsao Foundation. Programs include exercises, social activities, health screening, befriending and community support for seniors aged 60+.",
    address: "Blk 97 Whampoa Drive #01-01, Singapore 320097",
    hours: "Mon–Fri 9AM–5PM",
  },

  // ── Active Global Senior Care ────────────────────────────────
  {
    id: "aac-active-global-fernvale-glades",
    name: "Active Global Senior Care @ Fernvale Glades",
    lat: 1.3918,
    lng: 103.8762,
    category: "Active Ageing Centre",
    description:
      "Operated by Active Global. Programs include gentle aerobics, social activities, health monitoring and community support for seniors aged 60+.",
    address: "Blk 460 Fernvale Link, Singapore 791460",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-active-global-ghim-moh-edge",
    name: "Active Global Senior Care @ Ghim Moh Edge",
    lat: 1.3112,
    lng: 103.7882,
    category: "Active Ageing Centre",
    description:
      "Operated by Active Global. Programs include Zumba Gold, social activities, health screening and community support for seniors aged 60+.",
    address: "Blk 31A Ghim Moh Link, Singapore 271031",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-active-global-telok-blangah-parcview",
    name: "Active Global Senior Care @ Telok Blangah ParcView",
    lat: 1.2712,
    lng: 103.8098,
    category: "Active Ageing Centre",
    description:
      "Operated by Active Global. Programs include Zumba Gold, social activities, health monitoring and community support for seniors aged 60+.",
    address: "Blk 92 Telok Blangah St 31, Singapore 102092",
    hours: "Mon–Fri 9AM–5PM",
  },

  // ── Adventist Active Centre ──────────────────────────────────
  {
    id: "aac-adventist-golden-clover",
    name: "Adventist Active Centre @ Golden Clover",
    lat: 1.3272,
    lng: 103.8571,
    category: "Active Ageing Centre",
    description:
      "Operated by Adventist Community Services. Programs include senior fitness, social activities, health screening and community support for seniors aged 60+.",
    address: "Blk 196 Kim Keat Ave #01-506, Singapore 310196",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-adventist-golden-peony",
    name: "Adventist Active Centre @ Golden Peony",
    lat: 1.3497,
    lng: 103.7186,
    category: "Active Ageing Centre",
    description:
      "Operated by Adventist Community Services. Programs include senior fitness, social activities, health monitoring and community support for seniors aged 60+.",
    address: "Blk 530A Jurong West Ave 1 #01-907, Singapore 641530",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-adventist-kallang-trivista",
    name: "Adventist Active Centre @ Kallang Trivista",
    lat: 1.3142,
    lng: 103.8622,
    category: "Active Ageing Centre",
    description:
      "Operated by Adventist Community Services. Programs include senior fitness, social activities, health screening and community support for seniors aged 60+.",
    address: "Blk 8 Upper Boon Keng Road #01-02, Singapore 380008",
    hours: "Mon–Fri 9AM–5PM",
  },

  // ── HNF (Hua Mei / NTUC) ────────────────────────────────────
  {
    id: "aac-hnf-wellness-hougang",
    name: "HNF Wellness @ Hougang",
    lat: 1.3696,
    lng: 103.8911,
    category: "Active Ageing Centre",
    description:
      "Operated by Health and Nutrition Foundation. Programs include gentle aerobics, social activities, health monitoring and community support for seniors aged 60+.",
    address: "35 Hougang Ave 3, #04-01, Singapore 538840",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-hnf-wellness-buangkok",
    name: "HNF Wellness Club @ Buangkok",
    lat: 1.3835,
    lng: 103.8828,
    category: "Active Ageing Centre",
    description:
      "Operated by Health and Nutrition Foundation. Programs include chair yoga, stretching, social activities and community support for seniors aged 60+.",
    address: "Blk 999 Buangkok Crescent #01-01, Singapore 530999",
    hours: "Mon–Fri 9AM–5PM",
  },

  // ── Kwong Wai Shiu ───────────────────────────────────────────
  {
    id: "aac-kws-ccc-mcnair",
    name: "KWS CCC @ McNair",
    lat: 1.3189,
    lng: 103.8582,
    category: "Active Ageing Centre",
    description:
      "Operated by Kwong Wai Shiu Hospital. Programs include active ageing workouts, social activities, health monitoring and community support for seniors aged 60+.",
    address: "Blk 113 McNair Road, Singapore 320113",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-kwsc-macpherson",
    name: "KWSC @ MacPherson",
    lat: 1.3269,
    lng: 103.8863,
    category: "Active Ageing Centre",
    description:
      "Operated by Kwong Wai Shiu Hospital. Programs include Tai Chi, Qigong, social activities and community support for seniors aged 60+.",
    address: "82 Circuit Road #01-02, Singapore 370082",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-kwsc-st-george",
    name: "KWSC @ St George",
    lat: 1.3112,
    lng: 103.8601,
    category: "Active Ageing Centre",
    description:
      "Operated by Kwong Wai Shiu Hospital. Programs include Tai Chi, exercises, social activities and community support for seniors aged 60+.",
    address: "25 St George's Lane, Singapore 328048",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-kwsh-potong-pasir",
    name: "KWSH @ Potong Pasir",
    lat: 1.3306,
    lng: 103.8681,
    category: "Active Ageing Centre",
    description:
      "Operated by Kwong Wai Shiu Hospital. Programs include exercises, stretching, social activities and community support for seniors aged 60+.",
    address: "51 Potong Pasir Ave 1, Singapore 358074",
    hours: "Mon–Fri 9AM–5PM",
  },

  // ── PCF Sparkle Care ─────────────────────────────────────────
  {
    id: "aac-pcf-sparkle-care-braddell-heights",
    name: "PCF Sparkle Care AAC (Care) (Braddell Heights)",
    lat: 1.3534,
    lng: 103.8725,
    category: "Active Ageing Centre",
    description:
      "Operated by PCF Sparkle Care. Programs include strength and balance training, social activities, health monitoring and community support for seniors aged 60+.",
    address: "Blk 319 Serangoon Ave 2 #01-348, Singapore 550319",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-pcf-sparkle-care-eunos",
    name: "PCF Sparkle Care AAC (Care) (Eunos)",
    lat: 1.3225,
    lng: 103.9035,
    category: "Active Ageing Centre",
    description:
      "Operated by PCF Sparkle Care. Programs include strength and balance training, social activities, health screening and community support for seniors aged 60+.",
    address: "Blk 657 Jalan Tenaga #01-122, Singapore 410657",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-pcf-sparkle-care-shunfu",
    name: "PCF Sparkle Care AAC (Care) (Shunfu)",
    lat: 1.3515,
    lng: 103.8375,
    category: "Active Ageing Centre",
    description:
      "Operated by PCF Sparkle Care. Programs include strength and balance training, social activities, health monitoring and community support for seniors aged 60+.",
    address: "Blk 301 Shunfu Road #01-25, Singapore 570313",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-pcf-sparkle-care-yew-tee",
    name: "PCF Sparkle Care AAC (Care) (Yew Tee)",
    lat: 1.3971,
    lng: 103.7472,
    category: "Active Ageing Centre",
    description:
      "Operated by PCF Sparkle Care. Programs include strength and balance training, social activities, health screening and community support for seniors aged 60+.",
    address: "Blk 625 Choa Chu Kang St 62 #01-206, Singapore 680625",
    hours: "Mon–Fri 9AM–5PM",
  },
];
