import type { POI } from "@/types";

export const ACTIVE_AGEING_CENTRES_NEW: POI[] = [
  {
    id: "aac-ntuc-health-active-ageing-centre-care-wisma-geylang-serai",
    name: "NTUC Health Active Ageing Centre (Care) (Wisma Geylang Serai)",
    lat: 1.3165,
    lng: 103.8966,
    category: "Active Ageing Centre",
    description:
      "Operated by NTUC Health. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "1 Engku Aman Turn #01-01, Wisma Geylang Serai, Singapore 408528",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 9488 4575",
  },
  {
    id: "aac-ntuc-health-active-ageing-centre-gek-poh",
    name: "NTUC Health Active Ageing Centre (Gek Poh)",
    lat: 1.3487,
    lng: 103.6977,
    category: "Active Ageing Centre",
    description:
      "Operated by NTUC Health. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 1 Gek Poh Shopping Centre, 762 Jurong West St 75, Singapore 640762",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 8031 5061",
  },
  {
    id: "aac-ntuc-health-active-ageing-centre-kampung-kembangan",
    name: "NTUC Health Active Ageing Centre (Kampung Kembangan)",
    lat: 1.3232,
    lng: 103.9127,
    category: "Active Ageing Centre",
    description:
      "Operated by NTUC Health. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 11 Kampung Kembangan, 2 Lengkong Tiga, Singapore 417408",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 9058 6830",
  },
  {
    id: "aac-ntuc-health-active-ageing-centre-lengkok-bahru",
    name: "NTUC Health Active Ageing Centre (Lengkok Bahru)",
    lat: 1.2876,
    lng: 103.8123,
    category: "Active Ageing Centre",
    description:
      "Operated by NTUC Health. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 51 Lengkok Bahru #01-377, Singapore 150051",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6473 3387",
  },
  {
    id: "aac-ntuc-health-active-ageing-centre-mt-faber",
    name: "NTUC Health Active Ageing Centre (Mt. Faber)",
    lat: 1.2727,
    lng: 103.8229,
    category: "Active Ageing Centre",
    description:
      "Operated by NTUC Health. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 37 Telok Blangah Rise #01-304, Singapore 090037",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6590 4370",
  },
  {
    id: "aac-ntuc-health-active-ageing-centre-nanyang",
    name: "NTUC Health Active Ageing Centre (Nanyang)",
    lat: 1.3434,
    lng: 103.6909,
    category: "Active Ageing Centre",
    description:
      "Operated by NTUC Health. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 950 Jurong West St 91 #01-110, Singapore 640950",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 9876 4801",
  },
  {
    id: "aac-ntuc-health-active-ageing-centre-redhill",
    name: "NTUC Health Active Ageing Centre (Redhill)",
    lat: 1.2873,
    lng: 103.8183,
    category: "Active Ageing Centre",
    description:
      "Operated by NTUC Health. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 85 Redhill Close #01-536, Singapore 150085",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6473 8557",
  },
  {
    id: "aac-ntuc-health-active-ageing-centre-serangoon-central",
    name: "NTUC Health Active Ageing Centre (Serangoon Central)",
    lat: 1.3541,
    lng: 103.8725,
    category: "Active Ageing Centre",
    description:
      "Operated by NTUC Health. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 261 Serangoon Central Drive #01-01, Singapore 550261",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6715 6761",
  },
  {
    id: "aac-ntuc-health-active-ageing-centre-woodlands-east",
    name: "NTUC Health Active Ageing Centre (Woodlands East)",
    lat: 1.4381,
    lng: 103.7952,
    category: "Active Ageing Centre",
    description:
      "Operated by NTUC Health. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 888A Woodlands Drive 50 #02-762, Singapore 731888",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 9746 6558",
  },
  {
    id: "aac-thk-aac-amk-208",
    name: "THK AAC @ AMK 208",
    lat: 1.3654,
    lng: 103.8427,
    category: "Active Ageing Centre",
    description:
      "Operated by Thye Hua Kwan Moral Charities. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 208 Ang Mo Kio Ave 1 #01-1009, Singapore 560208",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6456 2611",
  },
  {
    id: "aac-thk-aac-amk-257",
    name: "THK AAC @ AMK 257",
    lat: 1.3702,
    lng: 103.8358,
    category: "Active Ageing Centre",
    description:
      "Operated by Thye Hua Kwan Moral Charities. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 257 Ang Mo Kio Ave 4 #01-200, Singapore 560257",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6459 9139",
  },
  {
    id: "aac-thk-aac-amk-645",
    name: "THK AAC @ AMK 645",
    lat: 1.3793,
    lng: 103.8422,
    category: "Active Ageing Centre",
    description:
      "Operated by Thye Hua Kwan Moral Charities. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 645 Ang Mo Kio Ave 6 #01-4808, Singapore 560645",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6554 7298",
  },
  {
    id: "aac-thk-aac-bedok",
    name: "THK AAC @ Bedok",
    lat: 1.3206,
    lng: 103.9347,
    category: "Active Ageing Centre",
    description:
      "Operated by Thye Hua Kwan Moral Charities. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 18 Bedok South Road #01-19, Singapore 460018",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6242 2483",
  },
  {
    id: "aac-thk-aac-boon-lay",
    name: "THK AAC @ Boon Lay",
    lat: 1.3495,
    lng: 103.7128,
    category: "Active Ageing Centre",
    description:
      "Operated by Thye Hua Kwan Moral Charities. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 213 Boon Lay Place #01-07, Singapore 640213",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6264 3455",
  },
  {
    id: "aac-thk-aac-bukit-batok",
    name: "THK AAC @ Bukit Batok",
    lat: 1.3462,
    lng: 103.7494,
    category: "Active Ageing Centre",
    description:
      "Operated by Thye Hua Kwan Moral Charities. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 207 Bukit Batok St 21 #01-178, Singapore 650207",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6566 5303",
  },
  {
    id: "aac-thk-aac-bukit-merah-view",
    name: "THK AAC @ Bukit Merah View",
    lat: 1.2841,
    lng: 103.8208,
    category: "Active Ageing Centre",
    description:
      "Operated by Thye Hua Kwan Moral Charities. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 118 Bukit Merah View #01-255, Singapore 151118",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6276 4761",
  },
  {
    id: "aac-thk-aac-cassia",
    name: "THK AAC @ Cassia",
    lat: 1.4325,
    lng: 103.7841,
    category: "Active Ageing Centre",
    description:
      "Operated by Thye Hua Kwan Moral Charities. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 351 Woodlands Ave 6 #01-03, Cassia@Woodlands, Singapore 730351",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6917 2849",
  },
  {
    id: "aac-thk-aac-chong-pang",
    name: "THK AAC @ Chong Pang",
    lat: 1.431,
    lng: 103.8311,
    category: "Active Ageing Centre",
    description:
      "Operated by Thye Hua Kwan Moral Charities. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 143 Yishun Ring Road #01-01, Singapore 760143",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 8368 6288",
  },
  {
    id: "aac-thk-aac-fengshan-101",
    name: "THK AAC @ Fengshan 101",
    lat: 1.3345,
    lng: 103.9379,
    category: "Active Ageing Centre",
    description:
      "Operated by Thye Hua Kwan Moral Charities. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 101 Bedok North Ave 4 #01-03, Singapore 460101",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6208 2653",
  },
  {
    id: "aac-thk-aac-fengshan-114",
    name: "THK AAC @ Fengshan 114",
    lat: 1.3305,
    lng: 103.9358,
    category: "Active Ageing Centre",
    description:
      "Operated by Thye Hua Kwan Moral Charities. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 114 Bedok North St 2 #01-152, Singapore 460114",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6245 6993",
  },
  {
    id: "aac-thk-aac-indus-79",
    name: "THK AAC @ Indus 79",
    lat: 1.2825,
    lng: 103.8308,
    category: "Active Ageing Centre",
    description:
      "Operated by Thye Hua Kwan Moral Charities. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 79 Indus Road #01-513, Singapore 160079",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6276 3283",
  },
  {
    id: "aac-thk-aac-kaki-bukit",
    name: "THK AAC @ Kaki Bukit",
    lat: 1.3305,
    lng: 103.9242,
    category: "Active Ageing Centre",
    description:
      "Operated by Thye Hua Kwan Moral Charities. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 544 Bedok North St 3 #01-05, Singapore 460544",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6241 6691",
  },
  {
    id: "aac-thk-aac-taman-jurong",
    name: "THK AAC @ Taman Jurong",
    lat: 1.335,
    lng: 103.7203,
    category: "Active Ageing Centre",
    description:
      "Operated by Thye Hua Kwan Moral Charities. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 399 Yung Sheng Road #01-04, Singapore 610399",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6795 1185",
  },
  {
    id: "aac-thk-aac-telok-blangah-crescent",
    name: "THK AAC @ Telok Blangah Crescent",
    lat: 1.2754,
    lng: 103.8207,
    category: "Active Ageing Centre",
    description:
      "Operated by Thye Hua Kwan Moral Charities. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 24 Telok Blangah Crescent #01-185, Singapore 090024",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6276 1216",
  },
  {
    id: "aac-thk-aac-toa-payoh-15",
    name: "THK AAC @ Toa Payoh 15",
    lat: 1.3359,
    lng: 103.8591,
    category: "Active Ageing Centre",
    description:
      "Operated by Thye Hua Kwan Moral Charities. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 15 Toa Payoh Lorong 7 #01-1011, Singapore 310015",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6251 6504",
  },
  {
    id: "aac-fei-yue-aac-bukit-batok-east",
    name: "Fei Yue AAC (Bukit Batok East)",
    lat: 1.348,
    lng: 103.758,
    category: "Active Ageing Centre",
    description:
      "Operated by Fei Yue Community Services. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 274 Bukit Batok East Ave 4 #01-342, Singapore 650274",
    hours: "Mon–Fri 9AM–5PM",
  },
  {
    id: "aac-fei-yue-aac-brickland",
    name: "Fei Yue AAC (Brickland)",
    lat: 1.36,
    lng: 103.7493,
    category: "Active Ageing Centre",
    description:
      "Operated by Fei Yue. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 370 Bukit Batok St 31 #01-23, Singapore 650370",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6950 6322",
  },
  {
    id: "aac-fei-yue-aac-buangkok-green",
    name: "Fei Yue AAC (Buangkok Green)",
    lat: 1.3848,
    lng: 103.8831,
    category: "Active Ageing Centre",
    description:
      "Operated by Fei Yue. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 993A Buangkok Green #01-01, Singapore 531993",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6914 2166",
  },
  {
    id: "aac-fei-yue-aac-fajar",
    name: "Fei Yue AAC (Fajar)",
    lat: 1.3813,
    lng: 103.7703,
    category: "Active Ageing Centre",
    description:
      "Operated by Fei Yue. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 443 Fajar Road #01-443, Singapore 670443",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6370 4162",
  },
  {
    id: "aac-fei-yue-aac-holland-close",
    name: "Fei Yue AAC (Holland Close)",
    lat: 1.3088,
    lng: 103.7962,
    category: "Active Ageing Centre",
    description:
      "Operated by Fei Yue. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 5A Holland Close #01-02, Singapore 271005",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6774 4044",
  },
  {
    id: "aac-fei-yue-aac-hougang-dewcourt",
    name: "Fei Yue AAC (Hougang Dewcourt)",
    lat: 1.3774,
    lng: 103.9037,
    category: "Active Ageing Centre",
    description:
      "Operated by Fei Yue. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 476 Hougang Ave 8 #01-478, Singapore 530476",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6202 4699",
  },
  {
    id: "aac-fei-yue-aac-hougang",
    name: "Fei Yue AAC (Hougang)",
    lat: 1.3716,
    lng: 103.8936,
    category: "Active Ageing Centre",
    description:
      "Operated by Fei Yue. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 810 Hougang Central #01-206, Singapore 530810",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6538 0234",
  },
  {
    id: "aac-fei-yue-aac-limbang",
    name: "Fei Yue AAC (Limbang)",
    lat: 1.3921,
    lng: 103.7441,
    category: "Active Ageing Centre",
    description:
      "Operated by Fei Yue. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 537 Choa Chu Kang North 6 #01-01, Singapore 680537",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6659 0616",
  },
  {
    id: "aac-fei-yue-aac-senja",
    name: "Fei Yue AAC (Senja)",
    lat: 1.3859,
    lng: 103.7624,
    category: "Active Ageing Centre",
    description:
      "Operated by Fei Yue. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 619 Senja Road #01-01, Singapore 670619",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6351 9555",
  },
  {
    id: "aac-fei-yue-aac-serangoon",
    name: "Fei Yue AAC (Serangoon)",
    lat: 1.3541,
    lng: 103.8712,
    category: "Active Ageing Centre",
    description:
      "Operated by Fei Yue. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 254 Serangoon Ave 3 #01-01, Singapore 550254",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6345 6567",
  },
  {
    id: "aac-fei-yue-aac-sunshine-court",
    name: "Fei Yue AAC (Sunshine Court)",
    lat: 1.3781,
    lng: 103.7389,
    category: "Active Ageing Centre",
    description:
      "Operated by Fei Yue. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 475 Choa Chu Kang Ave 3 #01-05, Singapore 680475",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6334 0180",
  },
  {
    id: "aac-st-lukes-eldercare-aac-care-anchorvale",
    name: "St Luke's ElderCare AAC (Care) @ Anchorvale",
    lat: 1.3965,
    lng: 103.8882,
    category: "Active Ageing Centre",
    description:
      "Operated by St Luke's ElderCare. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 339A Anchorvale Crescent #01-01, Singapore 541339",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6910 6023",
  },
  {
    id: "aac-st-lukes-eldercare-aac-care-ayer-rajah",
    name: "St Luke's ElderCare AAC (Care) @ Ayer Rajah",
    lat: 1.2935,
    lng: 103.7885,
    category: "Active Ageing Centre",
    description:
      "Operated by St Luke's ElderCare. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 80 Ayer Rajah Crescent #01-01, Singapore 139956",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6262 1501",
  },
  {
    id: "aac-st-lukes-eldercare-aac-care-bukit-timah",
    name: "St Luke's ElderCare AAC (Care) @ Bukit Timah",
    lat: 1.3388,
    lng: 103.7786,
    category: "Active Ageing Centre",
    description:
      "Operated by St Luke's ElderCare. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 1 Jalan Anak Bukit #B1-01, Singapore 588996",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6873 1772",
  },
  {
    id: "aac-st-lukes-eldercare-aac-care-changkat",
    name: "St Luke's ElderCare AAC (Care) @ Changkat",
    lat: 1.3463,
    lng: 103.956,
    category: "Active Ageing Centre",
    description:
      "Operated by St Luke's ElderCare. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 148 Simei St 1 #01-01, Singapore 520148",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6789 9956",
  },
  {
    id: "aac-st-lukes-eldercare-aac-care-chong-pang",
    name: "St Luke's ElderCare AAC (Care) @ Chong Pang",
    lat: 1.4317,
    lng: 103.8281,
    category: "Active Ageing Centre",
    description:
      "Operated by St Luke's ElderCare. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 105 Yishun Ring Road #01-135, Singapore 760105",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 8021 5194",
  },
  {
    id: "aac-st-lukes-eldercare-aac-care-clementi",
    name: "St Luke's ElderCare AAC (Care) @ Clementi",
    lat: 1.3167,
    lng: 103.7692,
    category: "Active Ageing Centre",
    description:
      "Operated by St Luke's ElderCare. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 336 Clementi Ave 2 #01-158, Singapore 120336",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6872 2210",
  },
  {
    id: "aac-st-lukes-eldercare-aac-care-nee-soon-central",
    name: "St Luke's ElderCare AAC (Care) @ Nee Soon Central",
    lat: 1.4246,
    lng: 103.8332,
    category: "Active Ageing Centre",
    description:
      "Operated by St Luke's ElderCare. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 769 Yishun Ring Road #01-3513, Singapore 760769",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6759 9053",
  },
  {
    id: "aac-st-lukes-eldercare-aac-care-nee-soon-east",
    name: "St Luke's ElderCare AAC (Care) @ Nee Soon East",
    lat: 1.4307,
    lng: 103.8373,
    category: "Active Ageing Centre",
    description:
      "Operated by St Luke's ElderCare. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 202 Yishun Ave 9 #01-02, Singapore 760202",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6481 5903",
  },
  {
    id: "aac-goodlife-studio-bedok",
    name: "Goodlife Studio (Bedok)",
    lat: 1.3287,
    lng: 103.9365,
    category: "Active Ageing Centre",
    description:
      "Operated by Montfort Care. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 135 Bedok North St 2 #01-130, Singapore 460135",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6312 3988",
  },
  {
    id: "aac-goodlife-studio-bukit-purmei",
    name: "Goodlife Studio (Bukit Purmei)",
    lat: 1.2748,
    lng: 103.8269,
    category: "Active Ageing Centre",
    description:
      "Operated by Montfort Care. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 113 Bukit Purmei Road #01-367, Singapore 090113",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6250 0244",
  },
  {
    id: "aac-goodlife-studio-katong",
    name: "Goodlife Studio (Katong)",
    lat: 1.3205,
    lng: 103.8633,
    category: "Active Ageing Centre",
    description:
      "Operated by Montfort Care. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 34 Whampoa West #01-83, Singapore 330034",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6345 3491",
  },
  {
    id: "aac-goodlife-studio-marine-parade",
    name: "Goodlife Studio (Marine Parade)",
    lat: 1.3038,
    lng: 103.9084,
    category: "Active Ageing Centre",
    description:
      "Operated by Montfort Care. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 73 Marine Drive #01-200, Singapore 440073",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6445 0570",
  },
  {
    id: "aac-goodlife-studio-tampines-142",
    name: "Goodlife Studio (Tampines 142)",
    lat: 1.3487,
    lng: 103.9449,
    category: "Active Ageing Centre",
    description:
      "Operated by Montfort Care. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 142 Tampines St 12 #01-354, Singapore 521142",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 9133 4877",
  },
  {
    id: "aac-goodlife-studio-tampines-235",
    name: "Goodlife Studio (Tampines 235)",
    lat: 1.343,
    lng: 103.9555,
    category: "Active Ageing Centre",
    description:
      "Operated by Montfort Care. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 235 Tampines St 21 #01-20, Singapore 520235",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 9674 3512",
  },
  {
    id: "aac-goodlife-studio-tampines-251",
    name: "Goodlife Studio (Tampines 251)",
    lat: 1.3528,
    lng: 103.9481,
    category: "Active Ageing Centre",
    description:
      "Operated by Montfort Care. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 251 Tampines St 21 #01-51, Singapore 520251",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 9734 1870",
  },
  {
    id: "aac-goodlife-studio-tiong-bahru",
    name: "Goodlife Studio (Tiong Bahru)",
    lat: 1.2917,
    lng: 103.8273,
    category: "Active Ageing Centre",
    description:
      "Operated by Montfort Care. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 3 Boon Tiong Road #01-01, Singapore 160003",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 8522 0537",
  },
  {
    id: "aac-goodlife-studio-yishun-riverwalk",
    name: "GoodLife Studio (Yishun Riverwalk)",
    lat: 1.4305,
    lng: 103.8435,
    category: "Active Ageing Centre",
    description:
      "Operated by Montfort Care. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 332 Yishun Ring Road #01-1500, Singapore 760332",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 9643 4032",
  },
  {
    id: "aac-goodlife-studio-yishun",
    name: "Goodlife Studio (Yishun)",
    lat: 1.4164,
    lng: 103.8336,
    category: "Active Ageing Centre",
    description:
      "Operated by Montfort Care. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 838 Yishun St 81 #01-125, Singapore 760838",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6484 8040",
  },
  {
    id: "aac-lions-befrienders-aac-ang-mo-kio-318",
    name: "Lions Befrienders AAC @Ang Mo Kio 318",
    lat: 1.3656,
    lng: 103.8476,
    category: "Active Ageing Centre",
    description:
      "Operated by Lions Befrienders. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 318 Ang Mo Kio Ave 3 #01-105, Singapore 560318",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6681 4900",
  },
  {
    id: "aac-lions-befrienders-aac-bendemeer-32",
    name: "Lions Befrienders AAC @Bendemeer 32",
    lat: 1.3198,
    lng: 103.8634,
    category: "Active Ageing Centre",
    description:
      "Operated by Lions Befrienders. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 32 Bendemeer Road #01-898, Singapore 330032",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6681 4904",
  },
  {
    id: "aac-lions-befrienders-aac-clementi-367366",
    name: "Lions Befrienders AAC @Clementi 367/366",
    lat: 1.3129,
    lng: 103.7716,
    category: "Active Ageing Centre",
    description:
      "Operated by Lions Befrienders. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 367 Clementi Ave 2 #01-462, Singapore 120367",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6681 4025",
  },
  {
    id: "aac-lions-befrienders-aac-clementi-420",
    name: "Lions Befrienders AAC @Clementi 420",
    lat: 1.31,
    lng: 103.7691,
    category: "Active Ageing Centre",
    description:
      "Operated by Lions Befrienders. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 420 Clementi Ave 1 #01-202, Singapore 120420",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6681 4908",
  },
  {
    id: "aac-lions-befrienders-aac-tampines-434",
    name: "Lions Befrienders AAC @Tampines 434",
    lat: 1.3592,
    lng: 103.9516,
    category: "Active Ageing Centre",
    description:
      "Operated by Lions Befrienders. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 434 Tampines St 43 #01-111, Singapore 520434",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6681 4928",
  },
  {
    id: "aac-lions-befrienders-aac-tampines-494e",
    name: "Lions Befrienders AAC @Tampines 494E",
    lat: 1.3631,
    lng: 103.9555,
    category: "Active Ageing Centre",
    description:
      "Operated by Lions Befrienders. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 494E Tampines St 43 #01-301, Singapore 527494",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6681 4940",
  },
  {
    id: "aac-lions-befrienders-aac-tampines-499c",
    name: "Lions Befrienders AAC @Tampines 499C",
    lat: 1.3595,
    lng: 103.9561,
    category: "Active Ageing Centre",
    description:
      "Operated by Lions Befrienders. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 499C Tampines Ave 9 #01-01, Singapore 523499",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6681 4924",
  },
  {
    id: "aac-st-andrews-aac-havelock",
    name: "St Andrew's AAC (Havelock)",
    lat: 1.2887,
    lng: 103.8288,
    category: "Active Ageing Centre",
    description:
      "Operated by St Andrew's Senior Care. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 22 Havelock Road #01-711, Singapore 160022",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6694 0967",
  },
  {
    id: "aac-st-andrews-aac-jurong-west",
    name: "St Andrew's AAC (Jurong West)",
    lat: 1.3464,
    lng: 103.6978,
    category: "Active Ageing Centre",
    description:
      "Operated by St Andrew's Senior Care. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 729 Jurong West Ave 5 #01-210, Singapore 640729",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6563 0343",
  },
  {
    id: "aac-st-andrews-aac-peace-connect-5",
    name: "St Andrew's AAC (Peace Connect @5)",
    lat: 1.3126,
    lng: 103.8725,
    category: "Active Ageing Centre",
    description:
      "Operated by St Andrew's Senior Care. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 5 Upper Boon Keng Road #01-10, Singapore 380005",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6291 4156",
  },
  {
    id: "aac-st-andrews-aac-peace-connect-8",
    name: "St Andrew's AAC (Peace Connect @8)",
    lat: 1.313,
    lng: 103.8704,
    category: "Active Ageing Centre",
    description:
      "Operated by St Andrew's Senior Care. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 8 Upper Boon Keng Road #01-01, Singapore 380008",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6392 0460",
  },
  {
    id: "aac-st-andrews-aac-tampines-changkat",
    name: "St Andrew's AAC (Tampines Changkat)",
    lat: 1.3516,
    lng: 103.9451,
    category: "Active Ageing Centre",
    description:
      "Operated by St Andrew's Senior Care. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 156 Tampines St 12 #01-700, Singapore 521156",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6588 3536",
  },
  {
    id: "aac-st-andrews-aac-woodlands",
    name: "St Andrew's AAC (Woodlands)",
    lat: 1.4395,
    lng: 103.7998,
    category: "Active Ageing Centre",
    description:
      "Operated by St Andrew's Senior Care. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 672 Woodlands Ring Road #01-1749, Singapore 730672",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6957 1745",
  },
  {
    id: "aac-st-andrews-aac-bedok-north",
    name: "St Andrew's AAC (Bedok North)",
    lat: 1.3298,
    lng: 103.9338,
    category: "Active Ageing Centre",
    description:
      "Operated by St Andrew's Senior Care. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 403 Bedok North Ave 3 #01-377, Singapore 460403",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6320 0536",
  },
  {
    id: "aac-st-andrews-aac-bedok-south",
    name: "St Andrew's AAC (Bedok South)",
    lat: 1.3206,
    lng: 103.9347,
    category: "Active Ageing Centre",
    description:
      "Operated by St Andrew's Senior Care. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 18 Bedok South Road #01-09, Singapore 460018",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6320 0506",
  },
  {
    id: "aac-st-andrews-aac-dover",
    name: "St Andrew's AAC (Dover)",
    lat: 1.3074,
    lng: 103.7836,
    category: "Active Ageing Centre",
    description:
      "Operated by St Andrew's Senior Care. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 23 Dover Crescent #01-07, Singapore 130023",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 9820 9109",
  },
  {
    id: "aac-allkin-aac-ang-mo-kio-420",
    name: "Allkin AAC @ Ang Mo Kio 420",
    lat: 1.365,
    lng: 103.8531,
    category: "Active Ageing Centre",
    description:
      "Operated by Allkin Singapore. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 420 Ang Mo Kio Ave 10 #01-861, Singapore 560420",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6038 4300",
  },
  {
    id: "aac-allkin-aac-ang-mo-kio-510",
    name: "Allkin AAC @ Ang Mo Kio 510",
    lat: 1.3734,
    lng: 103.8491,
    category: "Active Ageing Centre",
    description:
      "Operated by Allkin Singapore. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 510 Ang Mo Kio Ave 8 #01-2530, Singapore 560510",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6038 4380",
  },
  {
    id: "aac-allkin-aac-pasir-ris-476a",
    name: "Allkin AAC @ Pasir Ris 476A",
    lat: 1.3749,
    lng: 103.9578,
    category: "Active Ageing Centre",
    description:
      "Operated by Allkin Singapore. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 476A Pasir Ris Drive 6 #02-05, Singapore 511476",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6038 4360",
  },
  {
    id: "aac-allkin-aac-punggol-206a",
    name: "Allkin AAC @ Punggol 206A",
    lat: 1.3992,
    lng: 103.9015,
    category: "Active Ageing Centre",
    description:
      "Operated by Allkin Singapore. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 206A Punggol Place #01-01, Singapore 821206",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6038 4350",
  },
  {
    id: "aac-allkin-aac-punggol-677b",
    name: "Allkin AAC @ Punggol 677B",
    lat: 1.4054,
    lng: 103.9095,
    category: "Active Ageing Centre",
    description:
      "Operated by Allkin Singapore. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 677B Punggol Drive #01-01, Singapore 822677",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6038 4370",
  },
  {
    id: "aac-allkin-aac-sengkang-139",
    name: "Allkin AAC @ Sengkang 139",
    lat: 1.3889,
    lng: 103.9043,
    category: "Active Ageing Centre",
    description:
      "Operated by Allkin Singapore. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 139 Rivervale Crescent #01-01, Singapore 540139",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6038 4390",
  },
  {
    id: "aac-allkin-aac-sengkang-182",
    name: "Allkin AAC @ Sengkang 182",
    lat: 1.3905,
    lng: 103.9092,
    category: "Active Ageing Centre",
    description:
      "Operated by Allkin Singapore. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 182 Rivervale Crescent #01-01, Singapore 540182",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6038 4340",
  },
  {
    id: "aac-allkin-aac-sin-ming-25",
    name: "Allkin AAC @ Sin Ming 25",
    lat: 1.3553,
    lng: 103.8375,
    category: "Active Ageing Centre",
    description:
      "Operated by Allkin Singapore. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 25 Sin Ming Road #01-01, Singapore 570025",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6038 4320",
  },
  {
    id: "aac-allkin-aac-sin-ming-410",
    name: "Allkin AAC @ Sin Ming 410",
    lat: 1.3628,
    lng: 103.8355,
    category: "Active Ageing Centre",
    description:
      "Operated by Allkin Singapore. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 410 Sin Ming Ave #01-04, Singapore 570410",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6038 4330",
  },
  {
    id: "aac-care-corner-aac-care-tp131",
    name: "Care Corner AAC (Care) TP131",
    lat: 1.338,
    lng: 103.8433,
    category: "Active Ageing Centre",
    description:
      "Operated by Care Corner Singapore. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 131 Toa Payoh Lorong 1 #01-1571, Singapore 310131",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6255 5182",
  },
  {
    id: "aac-care-corner-aac-care-tp261a",
    name: "Care Corner AAC (Care) TP261A",
    lat: 1.3337,
    lng: 103.8557,
    category: "Active Ageing Centre",
    description:
      "Operated by Care Corner Singapore. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 261A Toa Payoh East #01-01, Singapore 311261",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6971 1199",
  },
  {
    id: "aac-care-corner-aac-tp106",
    name: "Care Corner AAC TP106",
    lat: 1.3404,
    lng: 103.8482,
    category: "Active Ageing Centre",
    description:
      "Operated by Care Corner Singapore. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 106 Toa Payoh Lorong 1 #01-349, Singapore 310106",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6266 7423",
  },
  {
    id: "aac-care-corner-aac-tp149",
    name: "Care Corner AAC TP149",
    lat: 1.3338,
    lng: 103.8438,
    category: "Active Ageing Centre",
    description:
      "Operated by Care Corner Singapore. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 149 Toa Payoh Lorong 1 #01-1641, Singapore 310149",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6258 3122",
  },
  {
    id: "aac-care-corner-aac-tp170",
    name: "Care Corner AAC TP170",
    lat: 1.3313,
    lng: 103.8427,
    category: "Active Ageing Centre",
    description:
      "Operated by Care Corner Singapore. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 170 Toa Payoh Lorong 1 #01-1747, Singapore 310170",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6352 7930",
  },
  {
    id: "aac-care-corner-aac-wl16",
    name: "Care Corner AAC WL16",
    lat: 1.4423,
    lng: 103.7779,
    category: "Active Ageing Centre",
    description:
      "Operated by Care Corner Singapore. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 16 Woodlands Ring Road #01-01, Singapore 730016",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6219 3767",
  },
  {
    id: "aac-care-corner-aac-wl569a",
    name: "Care Corner AAC WL569A",
    lat: 1.4301,
    lng: 103.7897,
    category: "Active Ageing Centre",
    description:
      "Operated by Care Corner Singapore. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 569A Woodlands Ave 1 #01-01, Singapore 731569",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6570 3547",
  },
  {
    id: "aac-precious-aac-compassvale-ancilla",
    name: "Precious AAC (Compassvale Ancilla)",
    lat: 1.3845,
    lng: 103.895,
    category: "Active Ageing Centre",
    description:
      "Operated by Precious Active Ageing Centre. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 273B Compassvale Link #01-01, Singapore 542273",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6384 9711",
  },
  {
    id: "aac-precious-aac-fajar-spring",
    name: "Precious AAC (Fajar Spring)",
    lat: 1.3825,
    lng: 103.7673,
    category: "Active Ageing Centre",
    description:
      "Operated by Precious. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 410 Fajar Road #01-413, Singapore 670410",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6497 6703",
  },
  {
    id: "aac-precious-aac-punggol-emerald",
    name: "Precious AAC (Punggol Emerald)",
    lat: 1.3944,
    lng: 103.9155,
    category: "Active Ageing Centre",
    description:
      "Operated by Precious. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 166A Punggol Central #01-01, Singapore 821166",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6443 5363",
  },
  {
    id: "aac-precious-aac-punggol-ripples",
    name: "Precious AAC (Punggol Ripples)",
    lat: 1.4018,
    lng: 103.8999,
    category: "Active Ageing Centre",
    description:
      "Operated by Precious. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 211A Punggol Walk #01-01, Singapore 821211",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6444 1053",
  },
  {
    id: "aac-precious-aac-skyterracedawson",
    name: "Precious AAC (SkyTerrace@Dawson)",
    lat: 1.2951,
    lng: 103.8112,
    category: "Active Ageing Centre",
    description:
      "Operated by Precious. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 92 Dawson Road #01-01, Singapore 142092",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6209 4170",
  },
  {
    id: "aac-precious-aac-sunshine-gardens",
    name: "Precious AAC (Sunshine Gardens)",
    lat: 1.3293,
    lng: 103.9311,
    category: "Active Ageing Centre",
    description:
      "Operated by Precious. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 412 Bedok North Ave 2 #01-01, Singapore 460412",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6912 7800",
  },
  {
    id: "aac-precious-aac-treegrovewoodlands",
    name: "Precious AAC (Treegrove@Woodlands)",
    lat: 1.4355,
    lng: 103.7994,
    category: "Active Ageing Centre",
    description:
      "Operated by Precious. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 660 Woodlands Ring Road #01-01, Singapore 730660",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6684 5386",
  },
  {
    id: "aac-sunlove-aac-chai-chee",
    name: "Sunlove AAC @ Chai Chee",
    lat: 1.3249,
    lng: 103.9426,
    category: "Active Ageing Centre",
    description:
      "Operated by Sunlove. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 54 Chai Chee St #01-07, Singapore 461054",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6876 0153",
  },
  {
    id: "aac-sunlove-aac-golden-saffron",
    name: "Sunlove AAC @ Golden Saffron",
    lat: 1.4158,
    lng: 103.8407,
    category: "Active Ageing Centre",
    description:
      "Operated by Sunlove. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 506B Yishun Ave 4 #01-01, Singapore 762506",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6462 2032",
  },
  {
    id: "aac-sunlove-aac-marsiling",
    name: "Sunlove AAC @ Marsiling",
    lat: 1.4399,
    lng: 103.7767,
    category: "Active Ageing Centre",
    description:
      "Operated by Sunlove. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 2 Marsiling Road #01-07, Singapore 730002",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6367 6615",
  },
  {
    id: "aac-sunlove-aac-serangoon",
    name: "Sunlove AAC @ Serangoon",
    lat: 1.3568,
    lng: 103.8731,
    category: "Active Ageing Centre",
    description:
      "Operated by Sunlove. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 212 Serangoon Ave 4 #01-15, Singapore 550212",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6970 1269",
  },
  {
    id: "aac-sunlove-aac-whampoa-dew",
    name: "Sunlove AAC @ Whampoa Dew",
    lat: 1.3273,
    lng: 103.8528,
    category: "Active Ageing Centre",
    description:
      "Operated by Sunlove. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 103 Jalan Rajah #01-261, Singapore 321103",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6925 6370",
  },
  {
    id: "aac-touchpointamk-433",
    name: "TOUCHpoint@AMK 433",
    lat: 1.3681,
    lng: 103.8544,
    category: "Active Ageing Centre",
    description:
      "Operated by TOUCH Community Services. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 433 Ang Mo Kio Ave 10 #01-1621, Singapore 560433",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6804 6568",
  },
  {
    id: "aac-touchpointwellington-513",
    name: "TOUCHpoint@Wellington 513",
    lat: 1.4542,
    lng: 103.8201,
    category: "Active Ageing Centre",
    description:
      "Operated by TOUCH Community Services. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 513 Wellington Circle #01-01, Singapore 750513",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6481 8232",
  },
  {
    id: "aac-touchpointyishun-162",
    name: "TOUCHpoint@Yishun 162",
    lat: 1.4331,
    lng: 103.8324,
    category: "Active Ageing Centre",
    description:
      "Operated by TOUCH Community Services. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 162 Yishun St 11 #01-200, Singapore 760162",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6257 0540",
  },
  {
    id: "aac-touchpointyishun-436",
    name: "TOUCHpoint@Yishun 436",
    lat: 1.4214,
    lng: 103.8461,
    category: "Active Ageing Centre",
    description:
      "Operated by TOUCH Community Services. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 436 Yishun Ave 11 #01-51, Singapore 760436",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6481 4158",
  },
  {
    id: "aac-aac-care-teck-whye-vista",
    name: "AAC (Care) @ Teck Whye Vista",
    lat: 1.3802,
    lng: 103.7526,
    category: "Active Ageing Centre",
    description:
      "Operated by REACH Community Services. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 139 Teck Whye Lane #01-305, Singapore 680139",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 8685 1879",
  },
  {
    id: "aac-adventist-nursing-and-rehab-centre",
    name: "Adventist Nursing and Rehab Centre",
    lat: 1.3215,
    lng: 103.923,
    category: "Active Ageing Centre",
    description:
      "Operated by Adventist Home. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "50 Jalan Khairuddin, Singapore 457524",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6760 0266",
  },
  {
    id: "aac-hnfpcf-sparkle-care-aac-tampines-813",
    name: "HNF-PCF Sparkle Care AAC @ Tampines 813",
    lat: 1.347,
    lng: 103.9364,
    category: "Active Ageing Centre",
    description:
      "Operated by Home Nursing Foundation. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 813 Tampines Ave 4 #01-107, Singapore 520813",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6244 4600",
  },
  {
    id: "aac-hnfpcf-sparkle-care-aac-tampines-922",
    name: "HNF-PCF Sparkle Care AAC @ Tampines 922",
    lat: 1.3475,
    lng: 103.9408,
    category: "Active Ageing Centre",
    description:
      "Operated by Home Nursing Foundation. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 922 Tampines St 91 #01-335, Singapore 520922",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6854 5555",
  },
  {
    id: "aac-reach-senior-centre-jalan-membina",
    name: "REACH Senior Centre @ Jalan Membina",
    lat: 1.2857,
    lng: 103.8268,
    category: "Active Ageing Centre",
    description:
      "Operated by REACH Community Services. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 18 Jalan Membina #01-01, Singapore 164018",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 9431 0161",
  },
  {
    id: "aac-chinatown-aac-chin-swee",
    name: "Chinatown AAC (Chin Swee)",
    lat: 1.2871,
    lng: 103.8416,
    category: "Active Ageing Centre",
    description:
      "Operated by Kreta Ayer Seniors Activity Centre. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 52 Chin Swee Road #01-137, Singapore 160052",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6533 3202",
  },
  {
    id: "aac-chinatown-aac-jalan-kukoh",
    name: "Chinatown AAC (Jalan Kukoh)",
    lat: 1.2861,
    lng: 103.833,
    category: "Active Ageing Centre",
    description:
      "Operated by Kreta Ayer Seniors Activity Centre. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 1 Jalan Kukoh #01-15, Singapore 162001",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6732 1286",
  },
  {
    id: "aac-loving-heart-aac-229-jurong-east",
    name: "Loving Heart AAC (229 Jurong East)",
    lat: 1.3418,
    lng: 103.738,
    category: "Active Ageing Centre",
    description:
      "Operated by Loving Heart Multi-Service Centre. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 229 Jurong East St 21 #01-108, Singapore 600229",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6897 4766",
  },
  {
    id: "aac-loving-heart-aac-318a-jurong-east",
    name: "Loving Heart AAC (318A Jurong East)",
    lat: 1.3476,
    lng: 103.7311,
    category: "Active Ageing Centre",
    description:
      "Operated by Loving Heart Multi-Service Centre. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 318A Jurong East St 31 #02-01, Singapore 601318",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6897 2646",
  },
  {
    id: "aac-sascocompassvale",
    name: "SASCO@Compassvale",
    lat: 1.3877,
    lng: 103.9006,
    category: "Active Ageing Centre",
    description:
      "Operated by SASCO Senior Citizens' Home. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 228C Compassvale Walk #01-01, Singapore 543228",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 8778 1474",
  },
  {
    id: "aac-sascokhatib",
    name: "SASCO@Khatib",
    lat: 1.416,
    lng: 103.8351,
    category: "Active Ageing Centre",
    description:
      "Operated by SASCO Senior Citizens' Home. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 845 Yishun Ring Road #01-3636, Singapore 760845",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 9834 9450",
  },
  {
    id: "aac-sascowestcoast",
    name: "SASCO@WestCoast",
    lat: 1.3038,
    lng: 103.7643,
    category: "Active Ageing Centre",
    description:
      "Operated by SASCO Senior Citizens' Home. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 726 West Coast Road #01-01, Singapore 120726",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 9838 9974",
  },
  {
    id: "aac-tzu-chi-glow-nanyang",
    name: "Tzu Chi GLOW @ Nanyang",
    lat: 1.3455,
    lng: 103.7176,
    category: "Active Ageing Centre",
    description:
      "Operated by Tzu Chi Foundation. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 519 Jurong West St 52 #01-282, Singapore 640519",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6859 1962",
  },
  {
    id: "aac-tzu-chi-seen-bukit-batok",
    name: "Tzu Chi SEEN @ Bukit Batok",
    lat: 1.3484,
    lng: 103.7535,
    category: "Active Ageing Centre",
    description:
      "Operated by Tzu Chi Foundation. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 227 Bukit Batok Central #01-225, Singapore 650227",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6355 9066",
  },
  {
    id: "aac-tzu-chi-seennanyang",
    name: "Tzu Chi SEEN@Nanyang",
    lat: 1.3433,
    lng: 103.6917,
    category: "Active Ageing Centre",
    description:
      "Operated by Tzu Chi Foundation. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 949 Jurong West St 91 #01-108, Singapore 640949",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6355 9068",
  },
  {
    id: "aac-careelderlycircuit",
    name: "CareElderly@Circuit",
    lat: 1.3262,
    lng: 103.8871,
    category: "Active Ageing Centre",
    description:
      "Operated by Christian Community Services Society. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 62 Circuit Road #01-340, Singapore 370062",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6747 8782",
  },
  {
    id: "aac-careelderlygolden-ginger",
    name: "CareElderly@Golden Ginger",
    lat: 1.4402,
    lng: 103.8289,
    category: "Active Ageing Centre",
    description:
      "Operated by Christian Community Services Society. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 380A Yishun Ave 11 #01-01, Singapore 761380",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6906 3571",
  },
  {
    id: "aac-econlife-hub",
    name: "ECONLIFE! Hub",
    lat: 1.391,
    lng: 103.8841,
    category: "Active Ageing Centre",
    description:
      "Operated by ECON Healthcare. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 311 Sengkang East Way #01-01, Singapore 541311",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6385 4946",
  },
  {
    id: "aac-econlife-hub-yung-kuang",
    name: "ECONLIFE! Hub @ Yung Kuang",
    lat: 1.33,
    lng: 103.7226,
    category: "Active Ageing Centre",
    description:
      "Operated by ECON Healthcare. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 163 Yung Kuang Road #01-01, Singapore 610163",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6496 1332",
  },
  {
    id: "aac-faithacts-commonwealth-drive",
    name: "FaithActs (Commonwealth Drive)",
    lat: 1.3083,
    lng: 103.8002,
    category: "Active Ageing Centre",
    description:
      "Operated by FaithActs. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 103 Commonwealth Drive #01-01, Singapore 140103",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6339 7611",
  },
  {
    id: "aac-faithacts-margaret-drive",
    name: "FaithActs (Margaret Drive)",
    lat: 1.2978,
    lng: 103.7977,
    category: "Active Ageing Centre",
    description:
      "Operated by FaithActs. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 37 Margaret Drive #01-01, Singapore 141037",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6339 7611",
  },
  {
    id: "aac-house-of-joy-mountbatten",
    name: "House of Joy Mountbatten",
    lat: 1.2999,
    lng: 103.8895,
    category: "Active Ageing Centre",
    description:
      "Operated by CHCSA. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 77 Mountbatten Road #01-01, Singapore 437751",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6348 8019",
  },
  {
    id: "aac-moral-aac-kaki-bukit",
    name: "Moral AAC @ Kaki Bukit",
    lat: 1.3307,
    lng: 103.9228,
    category: "Active Ageing Centre",
    description:
      "Operated by Chee Hwan Kog Moral Promoting Society. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 542 Bedok North St 3 #01-01, Singapore 460542",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6448 6247",
  },
  {
    id: "aac-orange-valley-aac-woodlands-peak",
    name: "Orange Valley AAC @ Woodlands Peak",
    lat: 1.4368,
    lng: 103.7894,
    category: "Active Ageing Centre",
    description:
      "Operated by Orange Valley. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 892C Woodlands Drive 50 #01-01, Singapore 733892",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6362 1756",
  },
  {
    id: "aac-snm-aac-carewoodlands",
    name: "SNM AAC (Care)@Woodlands",
    lat: 1.4409,
    lng: 103.7801,
    category: "Active Ageing Centre",
    description:
      "Operated by Sree Narayana Mission. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 3 Marsiling Road #01-01, Singapore 739108",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6362 5152",
  },
  {
    id: "aac-vanguard-aac-care-senja",
    name: "Vanguard AAC (Care) @ Senja",
    lat: 1.3851,
    lng: 103.7604,
    category: "Active Ageing Centre",
    description:
      "Operated by Vanguard Healthcare. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 628 Senja Road #01-01, Singapore 670628",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 9176 2060",
  },
  {
    id: "aac-vanguard-aac-care-woodlands",
    name: "Vanguard AAC (Care) @ Woodlands",
    lat: 1.437,
    lng: 103.7832,
    category: "Active Ageing Centre",
    description:
      "Operated by Vanguard Healthcare. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 903 Woodlands Drive 50 #01-01, Singapore 730903",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 8028 1631",
  },
  {
    id: "aac-4s-aac-eunos-crescent",
    name: "4S AAC @ Eunos Crescent",
    lat: 1.3221,
    lng: 103.9031,
    category: "Active Ageing Centre",
    description:
      "Operated by 4S. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 9A Eunos Crescent #01-2606, Singapore 401009",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6742 1321",
  },
  {
    id: "aac-awwa-aac",
    name: "AWWA AAC",
    lat: 1.3704,
    lng: 103.8777,
    category: "Active Ageing Centre",
    description:
      "Operated by AWWA. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 9 Lorong Napiri #01-01, Singapore 547529",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6511 6690",
  },
  {
    id: "aac-bcare-aac-compassvale",
    name: "BCARE AAC @ Compassvale",
    lat: 1.3823,
    lng: 103.8945,
    category: "Active Ageing Centre",
    description:
      "Operated by BCARE. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 277B Compassvale Link #01-01, Singapore 542277",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6610 0802",
  },
  {
    id: "aac-chong-hua-tong-aac",
    name: "Chong Hua Tong AAC",
    lat: 1.4434,
    lng: 103.7779,
    category: "Active Ageing Centre",
    description:
      "Operated by Chong Hua Tong. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 18 Marsiling Lane #01-313, Singapore 730018",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6294 3448",
  },
  {
    id: "aac-cornerstonechengsan-aac",
    name: "Cornerstone@ChengSan AAC",
    lat: 1.3726,
    lng: 103.8549,
    category: "Active Ageing Centre",
    description:
      "Operated by Cornerstone Community Services. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 528 Ang Mo Kio Ave 10 #01-2441, Singapore 560528",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6988 6967",
  },
  {
    id: "aac-filoschai-chee",
    name: "Filos@Chai Chee",
    lat: 1.3249,
    lng: 103.9241,
    category: "Active Ageing Centre",
    description:
      "Operated by Filos Community Services. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 29 Chai Chee Ave #01-186, Singapore 461029",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6244 8107",
  },
  {
    id: "aac-frcs-aac",
    name: "FRCS AAC",
    lat: 1.2971,
    lng: 103.7971,
    category: "Active Ageing Centre",
    description:
      "Operated by FRCS. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 55 Strathmore Ave #01-01, Singapore 141055",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 8886 0545",
  },
  {
    id: "aac-geylang-east-aac",
    name: "Geylang East AAC",
    lat: 1.3181,
    lng: 103.8836,
    category: "Active Ageing Centre",
    description:
      "Operated by Geylang East Home. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 6 Geylang East Central #01-01, Singapore 389706",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6842 6643",
  },
  {
    id: "aac-jalan-besar-aac",
    name: "Jalan Besar AAC",
    lat: 1.3111,
    lng: 103.8587,
    category: "Active Ageing Centre",
    description:
      "Operated by Jalan Besar AAC. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 2 Jalan Besar #01-20, Singapore 208956",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6294 1160",
  },
  {
    id: "aac-jia-ying-aac",
    name: "Jia Ying AAC",
    lat: 1.3296,
    lng: 103.9388,
    category: "Active Ageing Centre",
    description:
      "Operated by Jia Ying. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 121 Bedok North St 1 #01-138, Singapore 460121",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6281 5025",
  },
  {
    id: "aac-lentor-health-aaccaretlr",
    name: "Lentor Health AAC(Care)@TLR",
    lat: 1.3389,
    lng: 103.849,
    category: "Active Ageing Centre",
    description:
      "Operated by Lentor Health. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 95 Toa Payoh Lorong 5 #01-59, Singapore 310095",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 9276 9318",
  },
  {
    id: "aac-muhammadiyah-aac",
    name: "Muhammadiyah AAC",
    lat: 1.4156,
    lng: 103.8368,
    category: "Active Ageing Centre",
    description:
      "Operated by Muhammadiyah Health. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 851 Yishun Ring Road #01-3531, Singapore 760851",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6259 0968",
  },
  {
    id: "aac-ren-ci-aac-care-bukit-batok-st-52",
    name: "Ren Ci AAC (Care) @ Bukit Batok St. 52",
    lat: 1.3572,
    lng: 103.7527,
    category: "Active Ageing Centre",
    description:
      "Operated by Ren Ci Hospital. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 524 Bukit Batok St 52 #01-01, Singapore 650524",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6665 2005",
  },
  {
    id: "aac-sheng-hong-aac-care-sennett",
    name: "Sheng Hong AAC (Care) @ Sennett",
    lat: 1.3144,
    lng: 103.9409,
    category: "Active Ageing Centre",
    description:
      "Operated by Sheng Hong Temple. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 64 Sennett Road #01-01, Singapore 466498",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6239 0933",
  },
  {
    id: "aac-stroke-support-station-jurong-point",
    name: "Stroke Support Station @ Jurong Point",
    lat: 1.3395,
    lng: 103.7067,
    category: "Active Ageing Centre",
    description:
      "Operated by Stroke Support Station. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "1 Jurong West Central 2 #03-07, Jurong Point, Singapore 648886",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 8066 5986",
  },
  {
    id: "aac-salvation-army-peacehaven-bedok-arena",
    name: "Salvation Army Peacehaven Bedok Arena",
    lat: 1.3261,
    lng: 103.9279,
    category: "Active Ageing Centre",
    description:
      "Operated by The Salvation Army. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 201 Bedok North St 1 #01-01, Singapore 460201",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6581 9225",
  },
  {
    id: "aac-thong-kheng-aac-queenstown",
    name: "Thong Kheng AAC (Queenstown)",
    lat: 1.2907,
    lng: 103.8024,
    category: "Active Ageing Centre",
    description:
      "Operated by Thong Kheng Seniors Activity Centre. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 166 Stirling Road #01-1229, Singapore 140166",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6278 3966",
  },
  {
    id: "aac-trans-focus-aac",
    name: "TRANS FOCUS AAC",
    lat: 1.3303,
    lng: 103.9232,
    category: "Active Ageing Centre",
    description:
      "Operated by TRANS Family Services. Programs include exercises, social activities, health monitoring, befriending and community support for seniors aged 60+.",
    address: "Blk 543 Bedok North St 3 #01-01, Singapore 460543",
    hours: "Mon–Fri 9AM–5PM",
    contact: "+65 6467 8191",
  },
];
